CREATE TABLE [dbo].[Dim_Employee](
	[PK_DimEmployee_SK] [int] IDENTITY(1,1) NOT NULL,
	[EMPLOYEE] [char](5) NULL,
	[RECORD_TYPE] [char](1) NULL,
	[NAME] [char](30) NULL,
	[ADDRESS] [char](30) NULL,
	[CITY] [char](24) NULL,
	[STATE] [char](2) NULL,
	[ZIP_CODE] [char](9) NULL,
	[PHONE] [numeric](10, 0) NULL,
	[SOCIAL_SECURITY_NO] [char](9) NULL,
	[SEX] [char](1) NULL,
	[BIRTHDATE] [date] NULL,
	[DATE_HIRE] [date] NULL,
	[DATE_TERMINATION] [date] NULL,
	[DATE_RAISE] [date] NULL,
	[PR_CARRY_OVER_YMD] [date] NULL,
	[ELIG_HOL_DATE] [date] NULL,
	[ELIG_DT_401K] [date] NULL,
	[COMMENTS_1] [char](40) NULL,
	[COMMENTS_2] [char](30) NULL,
	[COMMENTS_3] [char](20) NULL,
	[RATE_PREVIOUS] [numeric](9, 3) NULL,
	[DEPT_EMPLOYEE] [char](4) NULL,
	[WORKMAN_COMP] [numeric](4, 0) NULL,
	[PAY_TYPE] [char](1) NULL,
	[FREQUENCY] [char](1) NULL,
	[RATE] [numeric](9, 3) NULL,
	[SHIFT] [char](1) NULL,
	[DIFFERENTIAL] [numeric](4, 2) NULL,
	[MARITAL_STATUS] [char](1) NULL,
	[STATE_CODE] [char](2) NULL,
	[SUI] [char](2) NULL,
	[EMAIL_ADDR] [char](100) NULL,
	[ALPHA_SORT] [char](12) NULL,
	[VACATION_LEFT] [numeric](5, 2) NULL,
	[SICK_LEFT] [numeric](5, 2) NULL,
	[ETL_Batch] [varchar](1) NOT NULL,
	[ETL_Completed] [varchar](19) NOT NULL,
	[effective_date] [datetime] NOT NULL,
	[End_date] [datetime] NULL,
	[IsEffective] [varchar](1) NOT NULL,
 CONSTRAINT [PK_DimEmployee_SK] PRIMARY KEY CLUSTERED 
(
	[PK_DimEmployee_SK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

