CREATE TABLE [dw].[DimPurchaseOrder](
	[DimPurchaseOrder_Key] [int] IDENTITY(1,1) NOT NULL,
	[POH_PURCHASE_ORDER] [char](7) NULL,
	[POH_RECORD_NO] [char](4) NULL,
	[POA_CRITICAL_SUPPL] [char](1) NULL,
	[POA_APPROVED_SUPPL] [char](1) NULL,
	[POH_TERMS] [char](12) NULL,
	[POH_ORDER_TAX] [char](1) NULL,
	[POH_FLAG_INSURANCE] [char](1) NULL,
	[POH_BUYER] [char](3) NULL,
	[POH_SHIP_VIA] [char](15) NULL,
	[POH_CODE_FOB] [char](15) NULL,
	[POH_FLAG_RECV_CLOSED] [char](1) NULL,
	[POH_FLAG_ACCT_CLOSE_A] [char](1) NULL,
	[POH_FLAG_PRINT] [char](1) NULL,
	[POH_PO_SEQ] [char](2) NULL,
	[POH_USER_2] [char](30) NULL,
	[POH_FLAG_CERTS_REQD] [char](1) NULL,
	[POH_TEXT_FORMAT] [char](1) NULL,
	[POH_PREV_SEQ] [char](2) NULL,
	[POH_DIFF_DUE_DATE] [char](1) NULL,
	[POH_PHYS_CHEM] [char](1) NULL,
	[POH_PAY_WITH_CCARD] [char](1) NULL,
	[POH_REC_TYPE] [char](1) NULL,
	[POH_PART_PD] [numeric](14, 2) NULL,
	[POH_SB_PAID] [numeric](14, 2) NULL,
	[POH_DISCOUNT_A] [numeric](5, 4) NULL,
	[POL_PO_TYPE] [char](1) NULL,
	[POL_LOCATION] [char](2) NULL,
	[POL_DESCRIPTION] [char](30) NULL,
	[POL_PART_MFG_NO] [char](23) NULL,
	[DROPSHIPPO_FLAG] [char](1) NULL,
	[POL_FILL_EXTENSION] [numeric](1, 0) NULL,
	[POL_EXTENSION] [numeric](15, 2) NULL,
	[POL_FILLER10] [char](14) NULL,
	[POL_FILL_EXCH_EXT] [numeric](1, 0) NULL,
	[POL_REQUISITION_LINE] [numeric](3, 0) NULL,
	[POL_FILL_IVCOST] [numeric](1, 0) NULL,
	[POL_FILL_PT] [numeric](1, 0) NULL,
	[POL_FILL_VT] [numeric](1, 0) NULL,
	[POL_VAT_RULE] [numeric](3, 0) NULL,
	[POL_USE_PURPOSE] [numeric](3, 0) NULL,
	[POL_BOOK_USE_TAX] [bit] NULL,
	[POL_FLAG_REC_TYPE] [char](1) NULL,
	[Type1RecordHash] [varbinary](64) NULL,
	[Type2RecordHash] [varbinary](64) NULL,
	[SourceSystemName] [nvarchar](100) NOT NULL,
	[DWEffectiveStartDate] [datetime2](7) NOT NULL,
	[DWEffectiveEndDate] [datetime2](7) NOT NULL,
	[DWIsCurrent] [bit] NOT NULL,
	[LoadLogKey] [int] NOT NULL,
 CONSTRAINT [pk_DimPurchaseOrder] PRIMARY KEY CLUSTERED 
(
	[DimPurchaseOrder_Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO