CREATE TABLE [dw].[DimCustomerShipTo](
	[DimCustomerShipTo_Key] [int] IDENTITY(1,1) NOT NULL,
	[PrimaryCustomerID] [nchar](6) NOT NULL,
	[ShipToSeq] [nchar](6) NOT NULL,
	[ShipToCustomername] [nvarchar](30) NOT NULL,
	[ShipToAddress1] [nvarchar](30) NULL,
	[ShipToAddress2] [nvarchar](30) NULL,
	[ShipToAddress3] [nvarchar](30) NULL,
	[ShipToAddress4] [nvarchar](30) NULL,
	[ShipToCity] [nchar](15) NULL,
	[ShipToState] [nchar](2) NULL,
	[ShipToZip] [nchar](13) NULL,
	[ShipToCountry] [nchar](12) NULL,
	[ShipToAttention] [nvarchar](30) NULL,
	[ShipToTelephone] [nchar](13) NULL,
	[ShipToSalesperson] [nchar](3) NULL,
	[ShipToShipVia] [nchar](1) NULL,
	[ShipToBranch] [nchar](2) NULL,
	[ShipToTaxENo] [nchar](20) NULL,
	[ShipToTaxState] [nchar](2) NULL,
	[ShipToTaxZip] [nchar](13) NULL,
	[ShipToTax1] [nchar](3) NULL,
	[ShipToTax2] [nchar](3) NULL,
	[ShipToTax3] [nchar](3) NULL,
	[ShipToTax4] [nchar](3) NULL,
	[ShipToTax5] [nchar](3) NULL,
	[ShipToWhoLastChanged] [nvarchar](8) NULL,
	[ShipToTrmLastChanged] [numeric](2, 0) NULL,
	[ShipToDateLastChanged] [datetime] NULL,
	[ShipToPrimaryGroup] [nchar](2) NULL,
	[ShipToCarrierCD] [nchar](6) NULL,
	[Type1RecordHash] [varbinary](64) NULL,
	[Type2RecordHash] [varbinary](64) NULL,
	[SourceSystemName] [nvarchar](100) NOT NULL,
	[DWEffectiveStartDate] [datetime2](7) NOT NULL,
	[DWEffectiveEndDate] [datetime2](7) NOT NULL,
	[DWIsCurrent] [bit] NOT NULL,
	[LoadLogKey] [int] NOT NULL,
 CONSTRAINT [pk_DimCustomerShipTo] PRIMARY KEY CLUSTERED 
(
	[DimCustomerShipTo_Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
