CREATE TABLE [dw].[DimSalesOrder](
	[DimSalesOrder_Key] [int] IDENTITY(1,1) NOT NULL,
	[SalesOrderNumber] [nchar](7) NULL,
	[SalesOrderLine] [nchar](4) NULL,
	[OHCreationDate] [datetime] NULL,
	[OHDueDate] [datetime] NULL,
	[OHOrderSort] [nvarchar](20) NULL,
	[OHProjectType] [nvarchar](30) NULL,
	[OHBranch] [nchar](2) NULL,
	[OHShipVia] [nvarchar](20) NULL,
	[OHPrimaryGroup] [nchar](2) NULL,
	[OHShippingZone] [nchar](6) NULL,
	[OHDateLastChanged] [datetime] NULL,
	[OHLastChangedBy] [nvarchar](8) NULL,
	[OLDateLastChanged] [datetime] NULL,
	[OLastChangedBy] [nvarchar](8) NULL,
	[OLDateOrder] [datetime] NULL,
	[OLDateShipped] [datetime] NULL,
	[OLItemPromiseDate] [datetime] NULL,
	[OLDateItemProm] [datetime] NULL,
	[OLDateAddedDate] [datetime] NULL,
	[OLDeliverByDate] [datetime] NULL,
	[OHCustomerID] [nchar](6) NULL,
	[OLCustomerID] [nchar](6) NULL,
	[OHShipToSeq] [nchar](6) NULL,
	[OLShipToSeq] [nchar](6) NULL,
	[OHSalespersonID] [nvarchar](3) NULL,
	[OHQuoteNumber] [nchar](7) NULL,
	[OHGLAccount] [nchar](15) NULL,
	[OLPartID] [nchar](20) NULL,
	[OLCustomerPart] [nvarchar](20) NULL,
	[OLPriceGroupID] [nvarchar](20) NULL,
	[OLSOGroupID] [nvarchar](20) NULL,
	[OLUser1] [nvarchar](30) NULL,
	[OLUser2] [nvarchar](30) NULL,
	[OLTrackingNotes] [nvarchar](30) NULL,
	[OLUser4] [nvarchar](30) NULL,
	[OLLineShipVia] [nvarchar](30) NULL,
	[OLLineType] [nchar](1) NULL,
	[OLFlagSOtoWO] [nchar](1) NULL,
	[OLFlagPurchased] [nchar](1) NULL,
	[OLInactive] [bit] NULL,
	[Type1RecordHash] [varbinary](64) NULL,
	[Type2RecordHash] [varbinary](64) NULL,
	[SourceSystemName] [nvarchar](100) NOT NULL,
	[DWEffectiveStartDate] [datetime2](7) NOT NULL,
	[DWEffectiveEndDate] [datetime2](7) NOT NULL,
	[DWIsCurrent] [bit] NOT NULL,
	[LoadLogKey] [int] NOT NULL,
 CONSTRAINT [pk_DimSalesOrders] PRIMARY KEY CLUSTERED 
(
	[DimSalesOrder_Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) 


