CREATE TABLE [dw].[FactAROpenItems](
	[DimCustomer_Key] [int] NOT NULL,
	[DimGLAccount_Key] [int] NOT NULL,
	[DimDateInvoice_key] [int] NOT NULL,
	[DimDateTransaction_key] [int] NOT NULL,
	[DimSalesPerson_key] [int] NOT NULL,
	[CUSTOMER] [char](7) NULL,
	[INVOICE] [char](7) NULL,
	[BATCH_CODE] [char](2) NULL,
	[BATCH_NUM] [char](5) NULL,
	[BATCH_LINE] [char](4) NULL,
	[DATE_INVOICE] [date] NULL,
	[DATE_TRANSACTION] [date] NULL,
	[AMT_TRANS_TOTAL] [numeric](16, 2) NULL,
	[GL_ACCOUNT] [char](15) NULL,
	[AMT_INVOICE] [numeric](16, 2) NULL,
	[SALESPERSON] [char](3) NULL,
	[REFERENCE] [char](22) NULL,
	[TERRITORY] [char](2) NULL,
	[STATE] [char](2) NULL,
	[EXCHANGE_AMT] [numeric](16, 2) NULL,
	[EXCHANGE_AMT_TOT] [numeric](16, 2) NULL,
	[ORDER_NO] [char](7) NULL,
	[ORDER_SUFFIX] [char](4) NULL,
	[TERMS_CODE] [char](1) NULL,
	[DUE_DATE] [date] NULL,
	[DISC_DATE] [date] NULL,
	[FRT_AMT_CO_CURR] [numeric](11, 2) NULL,
	[TAX_AMT_CO_CURR] [numeric](11, 2) NULL,
	[FRT_AMT_OE_CURR] [numeric](11, 2) NULL,
	[TAX_AMT_OE_CURR] [numeric](11, 2) NULL,
	[PCK_NO] [numeric](7, 0) NULL,
	[TAXABLE_FLG] [bit] NULL,
	[Type1RecordHash] [varbinary](64) NULL
) ON [PRIMARY]
GO