CREATE TABLE [dw].[FactAPOpenItems](
	[DimVendor_Key] [int] NOT NULL,
	[DimGLAccount_Key] [int] NOT NULL,
	[DimDateInvoice_key] [int] NOT NULL,
	[DimDateInvoiceDue_Key] [int] NOT NULL,
	[VENDOR] [char](7) NULL,
	[INVOICE] [char](15) NULL,
	[BATCH_CODE] [char](2) NULL,
	[BATCH_NUM] [char](5) NULL,
	[BATCH_LINE] [char](4) NULL,
	[DATE_BATCH] [date] NULL,
	[AREA] [char](2) NULL,
	[GL_ACCOUNT] [char](15) NULL,
	[DATE_INVOICE] [date] NULL,
	[AMT_INVOICE] [numeric](16, 2) NULL,
	[DATE_INVOICE_DUE] [date] NULL,
	[DISCOUNT_INVOICE] [numeric](10, 2) NULL,
	[PURCHASE_ORDER] [char](7) NULL,
	[BUYER] [char](3) NULL,
	[CHECK_NUM] [char](20) NULL,
	[DATE_CHECK] [date] NULL,
	[CHECK_CODE] [char](1) NULL,
	[RECEIVER] [char](6) NULL,
	[JOB] [char](7) NULL,
	[SUFFIX] [char](4) NULL,
	[SEQ] [char](6) NULL,
	[CHECK_DESC] [char](30) NULL,
	[VOUCHER] [char](7) NULL,
	[PAYMENT_SEQ] [char](1) NULL,
	[PO_LINE] [char](3) NULL,
	[AMT_TRANSACTION] [numeric](16, 2) NULL,
	[FLAG_PAY_SELECT] [char](1) NULL,
	[FLAG_CK_CLEARED] [char](1) NULL,
	[USERID] [char](8) NULL,
	[PAY_ACH] [char](1) NULL,
	[INVC_TAXABLE_AMT] [numeric](16, 2) NULL,
	[Type1RecordHash] [varbinary](64) NULL
) ON [PRIMARY]
GO