CREATE TABLE [dw].[FactGLARDetail](
	[DimDatePostDate_Key] [int] NOT NULL,
	[DimDateTransDate_Key] [int] NOT NULL,
	[DimDateRetainDate_Key] [int] NOT NULL,
	[DimDateInvcDate_Key] [int] NOT NULL,
	[DimDateInvcDueDate_Key] [int] NOT NULL,
	[DimDateDiscDueDate_Key] [int] NOT NULL,
	[DimDatExchDate_Key] [int] NOT NULL,
	[DimDateLastChgDate_Key] [int] NOT NULL,
	[DimGLAccount_Key] [int] NOT NULL,
	[DimCustomer_Key] [int] NOT NULL,
	[GL_NUMBER] [char](15) NULL,
	[POST_DATE] [datetime] NULL,
	[BATCH] [char](5) NULL,
	[LINE] [numeric](5, 0) NULL,
	[SEQ] [numeric](8, 0) NULL,
	[USERID] [char](8) NULL,
	[CUST] [char](7) NULL,
	[CUST_NAME] [char](50) NULL,
	[INVOICE_NO] [char](25) NULL,
	[TRANS_DATE] [datetime] NULL,
	[RETAIN_DATE] [datetime] NULL,
	[INVC_DATE] [datetime] NULL,
	[INVC_DTE_J] [numeric](5, 0) NULL,
	[INVC_DUE_DATE] [datetime] NULL,
	[INVC_DUE_DTE_J] [numeric](5, 0) NULL,
	[DISC_DUE_DATE] [datetime] NULL,
	[DISC_DUE_DTE_J] [numeric](5, 0) NULL,
	[TRAN_TYPE] [numeric](2, 0) NULL,
	[TRTY_BRANCH] [char](2) NULL,
	[RETAIN] [bit] NULL,
	[SALSM] [char](3) NULL,
	[REFN] [char](15) NULL,
	[AREA] [char](2) NULL,
	[STATE] [char](2) NULL,
	[FACTOR_FLAG] [bit] NULL,
	[TERMS_CODE] [char](1) NULL,
	[PAYMENT_TYPE] [numeric](3, 0) NULL,
	[PREPAID_FLAG] [bit] NULL,
	[EXCH_VARIANCE_FLAG] [bit] NULL,
	[TAXABLE_FLG] [bit] NULL,
	[ORDER_NUM] [numeric](7, 0) NULL,
	[ORDER_SEQ] [numeric](4, 0) NULL,
	[EXCH_DATE] [datetime] NULL,
	[EXCH_OE_CURR] [char](3) NULL,
	[EXCH_OE_RATE] [numeric](10, 5) NULL,
	[EXCH_CMPNY_CURR] [char](3) NULL,
	[EXCH_CMPNY_RATE] [numeric](10, 5) NULL,
	[DB_CR_FLAG] [bit] NULL,
	[AMOUNT_CMPNY] [numeric](16, 2) NULL,
	[COST_CMPNY] [numeric](16, 2) NULL,
	[INVTOT_CMPNY] [numeric](16, 2) NULL,
	[FRT_AMT_CMPNY] [numeric](11, 2) NULL,
	[TAX_AMT_CMPNY] [numeric](11, 2) NULL,
	[INVC_DISC_CMPNY] [numeric](10, 2) NULL,
	[TAXABLE_AMT_CMPNY] [numeric](16, 2) NULL,
	[RETENTION_CMPNY] [numeric](16, 2) NULL,
	[AMOUNT_OE] [numeric](16, 2) NULL,
	[COST_OE] [numeric](16, 2) NULL,
	[INVTOT_OE] [numeric](16, 2) NULL,
	[FRT_AMT_OE] [numeric](11, 2) NULL,
	[TAX_AMT_OE] [numeric](11, 2) NULL,
	[INVC_DISC_OE] [numeric](10, 2) NULL,
	[TAXABL_AMT_OE] [numeric](16, 2) NULL,
	[RETENTION_OE] [numeric](16, 2) NULL,
	[EXPORT_TO_EXT_SYS] [bit] NULL,
	[PAYMENT_CURR] [char](3) NULL,
	[FILLER] [char](96) NULL,
	[TRMNL] [char](3) NULL,
	[LAST_CHG_DATE] [date] NULL,
	[LAST_CHG_TIME] [time](0) NULL,
	[LAST_CHG_PGM] [char](8) NULL,
	[LAST_CHG_BY] [char](8) NULL,
	[Type1RecordHash] [varbinary](8000) NULL
) ON [PRIMARY]
GO