CREATE TABLE [dwstage].[_V_Invoice](
	[SalesOrderNumber] [nchar](7) NULL,
	[SalesOrderLine] [nchar](4) NULL,
	[OLOrderSuffix] [nchar](3) NULL,
	[OHOrderSuffix] [nchar](4) NULL,
	[OLInvoiceNumber] [nchar](7) NULL,
	[OHCreationdate] [date] NULL,
	[DateOrderDue] [date] NULL,
	[OHDuedate] [date] NULL,
	[OHInvoiceNumber] [nchar](7) NULL,
	[OLDateDue] [date] NULL,
	[OHOrderSort] [nvarchar](20) NULL,
	[OHProjectType] [nvarchar](30) NULL,
	[OHBranch] [nchar](2) NULL,
	[OrderShipVia] [nvarchar](20) NULL,
	[OHPrimaryGroup] [nchar](2) NULL,
	[OHShippingZone] [nchar](6) NULL,
	[OLDateOrder] [date] NULL,
	[OLDateShipped] [date] NULL,
	[OLDateLineInvoiced] [date] NULL,
	[OLCustDueDate] [date] NULL,
	[OLBranch] [nchar](2) NULL,
	[OLShipVia] [nvarchar](20) NULL,
	[OLCustomerPart] [nvarchar](20) NULL,
	[OLInternationalFlag] [nchar](1) NULL,
	[OLBOMExplodeFlag] [nchar](1) NULL,
	[OLFlagTaxStatus] [nchar](1) NULL,
	[OLCreditMemoFlag] [nchar](1) NULL,
	[OLFlagRMA] [nchar](1) NULL,
	[OLBOMCompleteFlag] [nchar](1) NULL,
	[OLBOMParentLineNumber] [nchar](4) NULL,
	[OLSerializedFlag] [nchar](1) NULL,
	[OLUMInventory] [nchar](2) NULL,
	[OLProductLine] [nchar](2) NULL,
	[OLPriceGroupID] [nvarchar](20) NULL,
	[OLSOGroupID] [nvarchar](20) NULL,
	[OLUser1] [nvarchar](30) NULL,
	[OLUser2] [nvarchar](30) NULL,
	[OLTrackingNotes] [nvarchar](30) NULL,
	[OLUser4] [nvarchar](30) NULL,
	[OLUser5ShipVia] [nvarchar](30) NULL,
	[OLShippingZone] [nchar](6) NULL,
	[OLPhase] [nchar](4) NULL,
	[OLPriceDescription] [nvarchar](30) NULL,
	[OLLineType] [nchar](1) NULL,
	[Customer] [nchar](6) NULL,
	[OrderLineCustShipTo] [nchar](6) NULL,
	[OrderCustShipTo] [nchar](6) NULL,
	[Part] [nvarchar](20) NULL,
	[SalesPerson] [nchar](3) NULL,
	[GLAccount] [nchar](14) NULL,
	[Job] [nchar](6) NULL,
	[QtyOrdered] [decimal](13, 4) NULL,
	[QtyShipped] [decimal](13, 4) NULL,
	[QtyBO] [decimal](13, 4) NULL,
	[QtyOriginal] [decimal](13, 4) NULL,
	[Cost] [decimal](16, 6) NULL,
	[CostMaterial] [decimal](11, 2) NULL,
	[CostLabor] [decimal](11, 2) NULL,
	[CostOutside] [decimal](11, 2) NULL,
	[CostOverhead] [decimal](11, 2) NULL,
	[CostOther] [decimal](11, 2) NULL,
	[Margin] [decimal](7, 4) NULL,
	[Price] [decimal](16, 6) NULL,
	[ExtendedPrice] [decimal](16, 2) NULL,
	[TaxApply1] [nchar](1) NULL,
	[TaxApply2] [nchar](1) NULL,
	[TaxAmt1] [decimal](11, 2) NULL,
	[TaxAmt2] [decimal](11, 2) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
)