CREATE TABLE [dwstage].[INVENTORY_MSTR](
	[PART] [char](20) NULL,
	[LOCATION] [char](2) NULL,
	[CODE_ABC] [char](1) NULL,
	[PRODUCT_LINE] [char](2) NULL,
	[FILLER2] [char](2) NULL,
	[BIN] [char](6) NULL,
	[DESCRIPTION] [char](30) NULL,
	[UM_PURCHASING] [char](3) NULL,
	[UM_INVENTORY] [char](3) NULL,
	[FACTOR_CONVERSION] [numeric](11, 5) NULL,
	[QTY_ORDER] [numeric](12, 4) NULL,
	[QTY_SAFETY] [numeric](12, 4) NULL,
	[QTY_ONHAND] [numeric](12, 4) NULL,
	[QTY_REORDER] [numeric](12, 4) NULL,
	[QTY_ONORDER_PO] [numeric](12, 4) NULL,
	[QTY_ONORDER_WO] [numeric](12, 4) NULL,
	[QTY_REQUIRED] [numeric](12, 4) NULL,
	[AMT_COST] [numeric](12, 4) NULL,
	[FILLER4] [char](12) NULL,
	[QTY_USAGE_MO_01] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_02] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_03] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_04] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_05] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_06] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_07] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_08] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_09] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_10] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_11] [numeric](7, 0) NULL,
	[QTY_USAGE_MO_12] [numeric](7, 0) NULL,
	[PRIOR_USAGE] [numeric](7, 0) NULL,
	[DATE_LAST_USAGE] [char](6) NULL,
	[AMT_PRICE] [numeric](13, 5) NULL,
	[OBSOLETE_FLAG] [char](1) NULL,
	[CODE_BOM] [char](1) NULL,
	[CODE_DISCOUNT] [char](1) NULL,
	[CODE_TOTAL] [char](1) NULL,
	[CODE_SORT] [char](10) NULL,
	[QTY_RECVD_NOT_INSP] [numeric](7, 0) NULL,
	[QTY_MFG_REQMTS] [numeric](7, 0) NULL,
	[QTY_CURRENT_USAGE] [numeric](7, 0) NULL,
	[YEAR_LAST_ROLL] [numeric](2, 0) NULL,
	[DATE_LAST_AUDIT] [char](6) NULL,
	[CODE_EXTRA_DESC] [char](1) NULL,
	[PCT_ORDER_DISC] [numeric](4, 4) NULL,
	[TIME_MATERIAL_LEAD] [numeric](4, 0) NULL,
	[PRIM_DIM] [numeric](7, 4) NULL,
	[SEC_DIM] [numeric](7, 4) NULL,
	[QTY_BEGINNING] [numeric](11, 4) NULL,
	[AMT_BEG_COST] [numeric](11, 4) NULL,
	[FILLER] [char](4) NULL,
	[CODE_EXCEPTION] [char](1) NULL,
	[CODE_PERM_FIX] [char](1) NULL,
	[DATE_EXCEPTION] [char](6) NULL,
	[CTR_BACK_ORDER] [numeric](2, 0) NULL,
	[AMT_ALT_COST] [numeric](16, 6) NULL,
	[FILLER5] [char](2) NULL,
	[DATE_LAST_CHG] [char](6) NULL,
	[TIME_LAST_CHG] [char](8) NULL,
	[WHO_CHG_LAST] [char](8) NULL,
	[TRM_CHG_LAST] [numeric](2, 0) NULL,
	[LENGTH_RAW_MATL] [numeric](3, 0) NULL,
	[WIDTH_RAW_MATL] [numeric](3, 0) NULL,
	[DENSITY_RAW_MATL] [numeric](7, 5) NULL,
	[CODE_RM_SHAPE] [char](1) NULL,
	[QTY_LAST_ONHAND] [numeric](12, 4) NULL,
	[FILLER3] [char](12) NULL,
	[DATE_LAST_VERIFY] [char](6) NULL,
	[FLAG_LOT] [char](1) NULL,
	[FLAG_DROP] [char](1) NULL,
	[FLAG_6_COST] [char](1) NULL,
	[FLAG_SERIALIZE] [char](1) NULL,
	[FLAG_INACTIVE] [char](1) NULL,
	[FLAG_WARRANTY] [char](1) NULL,
	[USE_ZERO_LEAD] [char](1) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]

GO

