CREATE TABLE [dwstage].[RMA_HIST_LINES](
	[RMA_ID] [char](7) NULL,
	[ORDER_NO] [char](7) NULL,
	[ORDER_SUFFIX] [char](4) NULL,
	[RMA_LINE] [char](6) NULL,
	[REC_TYPE] [char](2) NULL,
	[SVC_PERF_SEQ] [char](6) NULL,
	[NOTES_SEQ] [char](6) NULL,
	[PART] [char](20) NULL,
	[LOCATION] [char](2) NULL,
	[PART_DESCRIPTION] [char](30) NULL,
	[CUSTOMER_PART] [char](20) NULL,
	[FLAG_LOT] [char](1) NULL,
	[FLAG_SERIALIZE] [char](1) NULL,
	[QTY_SHIPPED] [decimal](13, 4) NULL,
	[QTY_RETURNED] [decimal](13, 4) NULL,
	[QTY_RECEIVED] [decimal](13, 4) NULL,
	[DATE_RECEIVED] [char](8) NULL,
	[SERVICE_REQUESTED] [char](3) NULL,
	[ORDER_LINE] [char](4) NULL,
	[QTY_PERF_COMPLETE] [decimal](13, 4) NULL,
	[QTY_PERF_SCHED] [decimal](13, 4) NULL,
	[FILLER1] [char](200) NULL,
	[FILLER2] [char](108) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
	)
