CREATE TABLE [dwstage].[GL_AP_CHECK_DTL](
	[GL_NUMBER] [char](15) NULL,
	[POST_DATE] [char](8) NULL,
	[BATCH] [char](5) NULL,
	[LINE] [numeric](5, 0) NULL,
	[SEQ] [numeric](8, 0) NULL,
	[USERID] [char](8) NULL,
	[CUST_VENDOR] [char](7) NULL,
	[INVOICE_NO] [char](25) NULL,
	[CHECK_NAME] [char](50) NULL,
	[CHECK_NUMBER] [char](20) NULL,
	[CHECK_DATE] [char](8) NULL,
	[CHECK_CODE] [numeric](2, 0) NULL,
	[CHECK_DATE_SQL] [date] NULL,
	[CHECK_INVC_CODE] [bit] NULL,
	[CHECK_INVC_SEQ] [numeric](2, 0) NULL,
	[POST_DATE_SQL] [date] NULL,
	[INVC_DATE] [char](8) NULL,
	[INVC_DATE_SQL] [date] NULL,
	[TRANS_DATE] [char](8) NULL,
	[TRANS_DATE_SQL] [date] NULL,
	[TRAN_TYPE] [numeric](2, 0) NULL,
	[VOUCHER] [char](7) NULL,
	[TRTY_BRANCH] [char](2) NULL,
	[PURCHASE_ORDER] [char](7) NULL,
	[PARTIAL_FLAG] [bit] NULL,
	[REFUND_FLAG] [bit] NULL,
	[EXCH_DATE] [char](8) NULL,
	[EXCH_DATE_SQL] [date] NULL,
	[EXCH_VEND_CURR] [char](3) NULL,
	[EXCH_VEND_RATE] [numeric](10, 5) NULL,
	[EXCH_CMPNY_CURR] [char](3) NULL,
	[EXCH_CMPNY_RATE] [numeric](10, 5) NULL,
	[DB_CR_FLAG] [bit] NULL,
	[AMOUNT_CMPNY] [numeric](16, 2) NULL,
	[GROSS_INVC_CMPNY] [numeric](16, 2) NULL,
	[CHECK_GROSS_CMPNY] [numeric](16, 2) NULL,
	[CHECK_DISC_CMPNY] [numeric](11, 2) NULL,
	[CHECK_NET_CMPNY] [numeric](16, 2) NULL,
	[TAX_AMT_CMPNY] [numeric](16, 2) NULL,
	[RETENTION_AMT_CMPNY] [numeric](16, 2) NULL,
	[AMOUNT_VEND] [numeric](16, 2) NULL,
	[GROSS_INVC_VEND] [numeric](16, 2) NULL,
	[CHECK_GROSS_VEND] [numeric](16, 2) NULL,
	[CHECK_DISC_VEND] [numeric](11, 2) NULL,
	[CHECK_NET_VEND] [numeric](16, 2) NULL,
	[TAX_AMT_VEND] [numeric](16, 2) NULL,
	[RETENTION_AMT_VEND] [numeric](16, 2) NULL,
	[EXPORT_TO_EXT_SYS] [bit] NULL,
	[SYSTEM] [bit] NULL,
	[PAYMENT_CURR] [char](3) NULL,
	[FILLER] [char](96) NULL,
	[TRMNL] [char](3) NULL,
	[LAST_CHG_DATE] [date] NULL,
	[LAST_CHG_TIME] [time](0) NULL,
	[LAST_CHG_PGM] [char](8) NULL,
	[LAST_CHG_BY] [char](8) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]
GO