CREATE TABLE [dwstage].[GL_AP_DETAIL](
	[GL_NUMBER] [char](15) NULL,
	[POST_DATE] [char](8) NULL,
	[BATCH] [char](5) NULL,
	[LINE] [numeric](5, 0) NULL,
	[SEQ] [numeric](8, 0) NULL,
	[USERID] [char](8) NULL,
	[VENDOR] [char](7) NULL,
	[VENDOR_NAME] [char](50) NULL,
	[INVOICE_NO] [char](25) NULL,
	[POST_DATE_SQL] [date] NULL,
	[TRANS_DATE] [char](8) NULL,
	[TRANS_DATE_SQL] [date] NULL,
	[INVC_DATE] [char](8) NULL,
	[INVC_DATE_SQL] [date] NULL,
	[INVC_DTE_J] [numeric](5, 0) NULL,
	[INVC_DUE_DATE] [char](8) NULL,
	[INVC_DUE_DATE_SEQL] [date] NULL,
	[INVC_DUE_DTE_J] [numeric](5, 0) NULL,
	[DISC_DUE_DATE] [char](8) NULL,
	[DISC_DUE_DATE_SQL] [date] NULL,
	[DISC_DUE_DTE_J] [numeric](5, 0) NULL,
	[TRAN_TYPE] [numeric](2, 0) NULL,
	[AP_CODE] [numeric](2, 0) NULL,
	[TRTY_BRANCH] [char](2) NULL,
	[AREA] [char](2) NULL,
	[BUYER] [char](3) NULL,
	[PO_NUM] [char](7) NULL,
	[RECEIVER] [char](6) NULL,
	[WO] [char](7) NULL,
	[WO_SUFFIX] [char](4) NULL,
	[WO_SEQ] [numeric](6, 0) NULL,
	[WO_KEY_SEQ] [numeric](4, 0) NULL,
	[CHK_O_DESC] [char](30) NULL,
	[VOU_NUM] [char](7) NULL,
	[PART_PO] [char](1) NULL,
	[QUANTITY] [numeric](14, 4) NULL,
	[JOB_UPDATE] [bit] NULL,
	[INV_MESSAGE] [numeric](3, 0) NULL,
	[PO_LINE] [char](3) NULL,
	[PAY_SEL] [numeric](3, 0) NULL,
	[RETURN_NUM] [numeric](7, 0) NULL,
	[RETURN_SEQ] [numeric](3, 0) NULL,
	[RETURN] [bit] NULL,
	[ADJ_ACC_FLAG] [bit] NULL,
	[PACK_LIST] [char](16) NULL,
	[TAXABLE_FLG] [bit] NULL,
	[USE_TAX_FLAG] [bit] NULL,
	[TAX_CODE] [char](5) NULL,
	[VAT_RULE] [numeric](3, 0) NULL,
	[INCL_IN_VAT_RPT] [bit] NULL,
	[INVC_EXP_FLG] [bit] NULL,
	[EXCH_DATE] [char](8) NULL,
	[EXCH_DATE_SQL] [date] NULL,
	[EXCH_VEND_CURR] [char](3) NULL,
	[EXCH_VEND_RATE] [numeric](10, 5) NULL,
	[EXCH_CMPNY_CURR] [char](3) NULL,
	[EXCH_CMPNY_RATE] [numeric](10, 5) NULL,
	[DB_CR_FLAG] [bit] NULL,
	[AMOUNT_CMPNY] [numeric](16, 2) NULL,
	[INVC_AMT_CMPNY] [numeric](16, 2) NULL,
	[INVC_TAXBL_AMT_CMPNY] [numeric](16, 2) NULL,
	[INVC_DISCT_CMPNY] [numeric](10, 2) NULL,
	[FRT_CMPNY] [numeric](11, 2) NULL,
	[OTH_CMPNY] [numeric](11, 2) NULL,
	[INVC_TAX_AMT_CMPNY] [numeric](16, 2) NULL,
	[RETN_AMT_CMPNY] [numeric](16, 2) NULL,
	[AMOUNT_VEND] [numeric](16, 2) NULL,
	[INVC_AMT_VEND] [numeric](16, 2) NULL,
	[INVC_TAXABL_AMT_VEND] [numeric](16, 2) NULL,
	[INVC_DISCT_VEND] [numeric](10, 2) NULL,
	[FRT_VEND] [numeric](11, 2) NULL,
	[OTH_VEND] [numeric](11, 2) NULL,
	[INVC_TAX_AMT_VEND] [numeric](16, 2) NULL,
	[RETN_AMT_VEND] [numeric](16, 2) NULL,
	[EXPORT_TO_EXT_SYS] [bit] NULL,
	[FILLER] [char](99) NULL,
	[TRMNL] [char](3) NULL,
	[LAST_CHG_DATE] [date] NULL,
	[LAST_CHG_TIME] [time](0) NULL,
	[LAST_CHG_PGM] [char](8) NULL,
	[LAST_CHG_BY] [char](8) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]
GO