--USE [LK-GS-EDW]
--GO


CREATE TABLE dwstage.WORKCENTERS
(
	[MACHINE] [char](4) NULL,
	[STANDARD_COST] [numeric](10, 2) NULL,
	[STANDARD_BILL] [numeric](10, 2) NULL,
	[STANDARD_OVHD] [numeric](10, 2) NULL,
	[FIXED_OVHD] [numeric](10, 2) NULL,
	[PCE_WRK_EXCL] [char](1) NULL,
	[HOURS_MO] [numeric](8, 2) NULL,
	[HOURS_YR] [numeric](8, 2) NULL,
	[CAPACITY_LABOR] [numeric](8, 2) NULL,
	[CAPACITY_MACHINE] [numeric](8, 2) NULL,
	[WORKMANS_COMP] [char](4) NULL,
	[WC_DEPT] [char](4) NULL,
	[WC_NAME] [char](20) NULL,
	[NO_MACHINES] [numeric](4, 0) NULL,
	[NO_EMPLOYEES] [numeric](4, 0) NULL,
	[HOURS_WEEKDAY] [numeric](4, 2) NULL,
	[HOURS_SATURDAY] [numeric](4, 2) NULL,
	[HOURS_SUNDAY] [numeric](4, 2) NULL,
	[WC_SEQ] [numeric](4, 0) NULL,
	[WC_TYPE] [numeric](1, 0) NULL,
	[WC_EXCLUDE] [char](1) NULL,
	[BEL] [numeric](4, 2) NULL,
	[START_HR] [numeric](2, 0) NULL,
	[START_MIN] [numeric](2, 0) NULL,
	[FINITE] [char](1) NULL,
	[FLOAT] [numeric](4, 2) NULL,
	[FLOAT_TYPE] [numeric](1, 0) NULL,
	[SCHED_PCT_MOD] [numeric](6, 5) NULL,
	[CNTG_SETUP_RUN] [char](1) NULL,
	[CNTG_INTRASQ_SCHED] [char](1) NULL,
	[HID_WD] [char](1) NULL,
	[INF_DAYS_BEF_TDY] [numeric](3, 0) NULL,
	[INF_DAYS_AFT_TDY] [numeric](3, 0) NULL,
	[SETUP_CONSTRAINT] [char](1) NULL,
	[FILLER1] [char](3) NULL,
	[RUNTIME_CONSTRAINT] [char](1) NULL,
	[FILLER2] [char](3) NULL,
	[INITIAL_TOOLING] [char](1) NULL,
	[RUN_TOOLING] [char](1) NULL,
	[RECUR_SETUP_TOOLING] [char](1) NULL,
	[CONSUMED_TOOLING] [char](1) NULL,
	[UNATT_SETUP] [char](1) NULL,
	[UNATT_RUNTIME] [char](1) NULL,
	[UNATT_SETUP_HRS] [numeric](5, 3) NULL,
	[UNATT_RUN_HRS] [numeric](5, 3) NULL,
	[SETUP_UNATT_BETW_PRD] [char](1) NULL,
	[RUN_UNATT_BETW_PRD] [char](1) NULL,
	[CALENDAR_PURGE_DAYS] [numeric](3, 0) NULL,
	[USE_ZERO_FLOAT] [char](1) NULL,
	[APPROVAL_REQ] [char](1) NULL,
	[COST_POOL_CODE] [char](5) NULL,
	[CREWSIZE] [numeric](8, 4) NULL,
	[EARNINGS_CODE] [char](2) NULL,
	[PROJ_GROUP] [char](6) NULL,
	[OVHD_CALC] [char](1) NULL,
	[NESTING_INTRFC] [char](1) NULL,
	[YIELD] [numeric](6, 5) NULL,
	[SEPARATE_SETUP_RUN] [numeric](1, 0) NULL,
	[BACKFLUSH_LABOR] [numeric](1, 0) NULL,
	[FILLER3] [char](192) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]
GO


