--USE [LK-GS-EDW]
--GO



CREATE TABLE dwstage.QUOTE_HEADER
(
	[QUOTE_NO] [char](7) NULL,
	[RECORD_NO] [char](4) NULL,
	[QUOTE_SHIP_ID] [char](6) NULL,
	[RECORD_TYPE] [char](1) NULL,
	[CUSTOMER] [char](6) NULL,
	[FILL_CUSTOMER] [char](1) NULL,
	[SHIPTO] [char](6) NULL,
	[INVOICE] [char](6) NULL,
	[FILL_INVOICE] [char](1) NULL,
	[DATE_QUOTE] [char](6) NULL,
	[DATE_DUE] [char](6) NULL,
	[INSURANCE] [char](1) NULL,
	[QUOTE_TYPE] [char](1) NULL,
	[QUOTE_SUFFIX] [char](4) NULL,
	[CUSTOMER_PO] [char](15) NULL,
	[FILL_CUST_PO] [char](15) NULL,
	[MARK_INFO] [char](30) NULL,
	[CODE_FOB] [char](14) NULL,
	[TERMS] [char](10) NULL,
	[WAY_BILL] [char](19) NULL,
	[LAST_REC_NO] [numeric](4, 0) NULL,
	[DATE_SHIPPED] [char](6) NULL,
	[FLAG_PRINT] [char](1) NULL,
	[CODE_SORT] [char](20) NULL,
	[FLAG_SHIPPED] [char](1) NULL,
	[TRANS_METHOD] [char](10) NULL,
	[CERT_ENCL] [char](1) NULL,
	[EXPIRATION] [char](10) NULL,
	[WHO_GOT_IT] [char](20) NULL,
	[USER_1] [char](30) NULL,
	[USER_2] [char](30) NULL,
	[USER_3] [char](30) NULL,
	[USER_4] [char](30) NULL,
	[USER_5] [char](30) NULL,
	[FLAG_NO_BACKQUOTE] [char](1) NULL,
	[SALESPERSON] [char](3) NULL,
	[BRANCH] [char](2) NULL,
	[AREA] [char](2) NULL,
	[FREIGHT_ZONE] [char](10) NULL,
	[SHIP_VIA] [char](20) NULL,
	[QUOTE_DISCOUNT] [numeric](5, 4) NULL,
	[PRICE_CLASS] [char](1) NULL,
	[PRICE_CLASS_DISC] [numeric](5, 4) NULL,
	[TYPE_COMMISSION] [char](5) NULL,
	[GL_ACCOUNT] [char](15) NULL,
	[TAX_SOURCE] [char](1) NULL,
	[TAX_STATE] [char](2) NULL,
	[TAX_ZIP] [char](13) NULL,
	[TAX_GEO_CODE] [char](2) NULL,
	[TAX_1] [char](3) NULL,
	[TAX_2] [char](3) NULL,
	[TAX_3] [char](3) NULL,
	[TAX_4] [char](3) NULL,
	[TAX_5] [char](3) NULL,
	[TAX_6] [char](3) NULL,
	[TAX_7] [char](3) NULL,
	[TAX_8] [char](3) NULL,
	[TAX_9] [char](3) NULL,
	[TAX_10] [char](3) NULL,
	[TAX_APPLY_1] [char](1) NULL,
	[TAX_APPLY_2] [char](1) NULL,
	[TAX_APPLY_3] [char](1) NULL,
	[TAX_APPLY_4] [char](1) NULL,
	[TAX_APPLY_5] [char](1) NULL,
	[TAX_APPLY_6] [char](1) NULL,
	[TAX_APPLY_7] [char](1) NULL,
	[TAX_APPLY_8] [char](1) NULL,
	[TAX_APPLY_9] [char](1) NULL,
	[TAX_APPLY_10] [char](1) NULL,
	[CONTRACT] [numeric](6, 0) NULL,
	[QUOTE_SORT_2] [char](30) NULL,
	[QUOTE] [char](7) NULL,
	[FLAG_TIME_MATL] [char](1) NULL,
	[DATE_QUOTE_CNV] [char](8) NULL,
	[DATE_DUE_CNV] [char](8) NULL,
	[FLAG_PICKLIST] [char](1) NULL,
	[QUOTE_LOCATION] [char](2) NULL,
	[FLAG_IN_PROCESS] [char](1) NULL,
	[DATE_PO_EXPIRE] [char](8) NULL,
	[PRICE_SCHED_ID] [char](9) NULL,
	[QUOTE_APPROVED_BY] [char](8) NULL,
	[DATE_QUOTE_APPROVED] [char](8) NULL,
	[FLAG_PL_TYPE] [char](1) NULL,
	[FLAG_SPCD] [char](1) NULL,
	[PRICE_CATEGORY] [char](2) NULL,
	[COMPANY_CURRENCY] [char](3) NULL,
	[CATALOG_CURRENCY] [char](3) NULL,
	[QUOTE_CURRENCY] [char](3) NULL,
	[DATE_EXCH_FO_TC] [char](8) NULL,
	[EXCH_RATE_FO_TC] [numeric](10, 5) NULL,
	[DATE_EXCH_FC_TO] [char](8) NULL,
	[EXCH_RATE_FC_TO] [numeric](10, 5) NULL,
	[DATE_EXCH_FL_TO] [char](8) NULL,
	[EXCH_RATE_FL_TO] [numeric](10, 5) NULL,
	[DATE_EXCH_FL_TC] [char](8) NULL,
	[EXCH_RATE_FL_TC] [numeric](10, 5) NULL,
	[BUY_GRP_CUST_NO] [char](6) NULL,
	[FILL_BG_CUST_NO] [char](1) NULL,
	[BUY_GRP_ADRS_FLG] [char](1) NULL,
	[PAYMENT_TYPE] [char](2) NULL,
	[ICV_RESPONSE] [char](1) NULL,
	[ICV_STATUS] [char](1) NULL,
	[PREPAID_INVOICE] [char](1) NULL,
	[CC_FAIL_FLAG] [char](1) NULL,
	[CMEMO_TYPE] [char](1) NULL,
	[PAYMENT_REQUEST] [char](1) NULL,
	[SPAWNED_SHPMT_FLAG] [char](1) NULL,
	[ORIG_SHPMT_SEQ] [char](4) NULL,
	[PRO_NO] [char](20) NULL,
	[LUMP_SUM_FLAG] [char](1) NULL,
	[FILL_LSA] [numeric](1, 0) NULL,
	[LUMP_SUM_AMT] [numeric](15, 2) NULL,
	[QTE_CREATED_BY] [char](8) NULL,
	[QTE_CREATED_DATE] [char](8) NULL,
	[LANG_CD] [char](3) NULL,
	[QUICK_SHP_FLAG] [char](1) NULL,
	[SHP_HLD_FLAG] [char](2) NULL,
	[BLANKET_NO] [char](7) NULL,
	[TRACKING_NO] [char](30) NULL,
	[TRACKING_FLAG] [char](1) NULL,
	[ETA_DATE] [char](8) NULL,
	[CARTONS] [numeric](8, 0) NULL,
	[WEIGHT] [numeric](12, 4) NULL,
	[COMPLETE_SHIP] [char](1) NULL,
	[TRMS_DSC_DUE_DT] [char](8) NULL,
	[TRMS_DSC_AMT] [numeric](10, 2) NULL,
	[TRMS_DSC_CUR_AMT] [numeric](10, 2) NULL,
	[LINE_TEXT_FLAG] [char](1) NULL,
	[PREPAY_APPLY_FLAG] [char](1) NULL,
	[IVC_ASSIGN_FLAG] [char](1) NULL,
	[AUTO_FRT_FLAG] [char](1) NULL,
	[QUOTE_WON_LOSS_DATE] [char](8) NULL,
	[FACILITY] [char](3) NULL,
	[FILLER250] [char](250) NULL,
	[FILLER12] [char](12) NULL,
	[NO_DLVR_BEFORE_DATE] [char](8) NULL,
	[MUST_DLVR_BY_DATE] [char](8) NULL,
	[TRNSFR_LOCN] [char](2) NULL,
	[INTRANSIT_AUTO] [numeric](1, 0) NULL,
	[TRANSIT_NO] [numeric](7, 0) NULL,
	[FILLER176] [char](176) NULL,
	[TAX_ZONE_1] [char](2) NULL,
	[TAX_ZONE_2] [char](2) NULL,
	[TAX_ZONE_3] [char](2) NULL,
	[TAX_ZONE_4] [char](2) NULL,
	[TAX_ZONE_5] [char](2) NULL,
	[TAX_ZONE_6] [char](2) NULL,
	[TAX_ZONE_7] [char](2) NULL,
	[TAX_ZONE_8] [char](2) NULL,
	[TAX_ZONE_9] [char](2) NULL,
	[TAX_ZONE_10] [char](2) NULL,
	[PRE_QUOTE] [char](1) NULL,
	[SCRIPT_FLG] [char](1) NULL,
	[IVC_HLD_FLG] [numeric](6, 0) NULL,
	[PROJECT] [char](7) NULL,
	[CARRIER_ACCT] [char](25) NULL,
	[PROCESS_GRP] [char](1) NULL,
	[SHIP_ID] [int] NULL,
	[CONTRACT_FLG] [char](1) NULL,
	[PRICE_CATG_FLG] [char](1) NULL,
	[TAX_INDX_FLG] [char](1) NULL,
	[FILLER1] [char](1) NULL,
	[NO_OVER_SHP_QTY] [bit] NULL,
	[PRIMARY_GRP] [char](2) NULL,
	[SECONDARY_GRP] [char](2) NULL,
	[SRVC_TYPE] [smallint] NULL,
	[VAT_RULE_ID] [numeric](3, 0) NULL,
	[VAT_EXEMPT_TYPE] [numeric](3, 0) NULL,
	[TAX_IN_PRC_FLG] [bit] NULL,
	[TAX_IMPORT_FLG] [numeric](3, 0) NULL,
	[ORIG_PCK_NO] [char](7) NULL,
	[CNV_SHIP_DATE] [char](8) NULL,
	[PCK_NO] [char](7) NULL,
	[SHP_STATUS] [char](1) NULL,
	[IVC_BATCH] [char](5) NULL,
	[THRD_PRTY_FRT_CUST] [char](7) NULL,
	[CARRIER_CD] [char](6) NULL,
	[FLAG_DATA_CNV] [char](1) NULL,
	[FLAG_ALWAYS_DISCOUNT] [char](1) NULL,
	[DATE_LAST_CHG] [char](8) NULL,
	[TIME_LAST_CHG] [char](8) NULL,
	[LAST_CHG_BY] [char](8) NULL,
	[LAST_CHG_PGM] [char](8) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]
GO


