CREATE TABLE [dwstage].[INVENTORY_MST2](
	[PART] [char](20) NULL,
	[LOCATION] [char](2) NULL,
	[QTY_MAXIMUM] [numeric](7, 0) NULL,
	[HRS_STANDARD] [numeric](7, 3) NULL,
	[LBS] [numeric](9, 4) NULL,
	[CODE_SOURCE] [char](12) NULL,
	[NAME_VENDOR] [char](20) NULL,
	[TEXT_INFO1] [char](20) NULL,
	[TEXT_INFO2] [char](20) NULL,
	[DESCRIPTION_2] [char](30) NULL,
	[DESCRIPTION_3] [char](30) NULL,
	[AMT_COST_1] [numeric](11, 4) NULL,
	[AMT_COST_2] [numeric](11, 4) NULL,
	[AMT_COST_3] [numeric](11, 4) NULL,
	[FILLER] [char](52) NULL,
	[DATE_CYCLE] [char](6) NULL,
	[LIFO_BASE] [numeric](11, 4) NULL,
	[SIX_DECIMAL_COST] [numeric](14, 6) NULL,
	[WT_PER_FOOT] [numeric](9, 4) NULL,
	[CUTTING_CHARGE] [char](1) NULL,
	[SHP_CNV_FACTOR] [numeric](11, 5) NULL,
	[SHIP_UM] [char](3) NULL,
	[LENGTH] [numeric](6, 2) NULL,
	[WIDTH] [numeric](6, 2) NULL,
	[WARRANTY_TYPE] [char](2) NULL,
	[PROP_CODE] [char](10) NULL,
	[REQUIRES_INSP] [char](1) NULL,
	[BASE_PART] [char](1) NULL,
	[PRICE_CATG] [char](1) NULL,
	[ISSUE_UM] [char](3) NULL,
	[PART_PRICE_CODE] [char](3) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]

GO


