CREATE TABLE [dwstage].[ORDER_HIST_LINE](
	[INVOICE] [nvarchar](7) NULL,
	[ORDER_NO] [nvarchar](7) NULL,
	[ORDER_SUFFIX] [nvarchar](4) NULL,
	[ORDER_LINE] [nvarchar](4) NULL,
	[CUSTOMER] [nvarchar](6) NULL,
	[CUSTOMER_SHIP] [nvarchar](6) NULL,
	[NAME_CUST_SHIP] [nvarchar](30) NULL,
	[ADDRESS1_SHIP] [nvarchar](30) NULL,
	[ADDRESS2_SHIP] [nvarchar](30) NULL,
	[ADDRESS3_SHIP] [nvarchar](30) NULL,
	[ADDRESS4_SHIP] [nvarchar](30) NULL,
	[ADDRESS5_SHIP] [nvarchar](30) NULL,
	[CITY_SHIP] [nvarchar](15) NULL,
	[STATE_SHIP] [nvarchar](3) NULL,
	[ZIP_SHIP] [nvarchar](13) NULL,
	[COUNTRY_SHIP] [nvarchar](12) NULL,
	[ATTENTION_SHIP] [nvarchar](30) NULL,
	[FLAG_INTL_SHIP] [nvarchar](1) NULL,
	[CUSTOMER_PO] [nvarchar](30) NULL,
	[DATE_ORDER] [datetime2](0) NULL,
	[DATE_ORDER_DUE] [datetime2](0) NULL,
	[DATE_SHIPPED] [datetime2](0) NULL,
	[DATE_INVOICE] [datetime2](0) NULL,
	[COMP_DATE_INVOICE] [nvarchar](8) NULL,
	[AREA] [nvarchar](2) NULL,
	[SALESPERSON] [nvarchar](3) NULL,
	[BRANCH] [nvarchar](2) NULL,
	[SHIP_VIA] [nvarchar](20) NULL,
	[PRICE_CLASS] [nvarchar](1) NULL,
	[PRICE_CATEGORY] [nvarchar](2) NULL,
	[BUY_GRP_CUSTOMER] [nvarchar](6) NULL,
	[FLAG_ALWAYS_DISC] [nvarchar](1) NULL,
	[COMPANY_CURRENCY] [nvarchar](3) NULL,
	[CATALOG_CURRENCY] [nvarchar](3) NULL,
	[ORDER_CURRENCY] [nvarchar](3) NULL,
	[PART] [nvarchar](20) NULL,
	[LOCATION] [nvarchar](2) NULL,
	[DESCRIPTION] [nvarchar](30) NULL,
	[CUSTOMER_PART] [nvarchar](20) NULL,
	[FLAG_CONFIG_PART] [nvarchar](1) NULL,
	[BIN] [nvarchar](4) NULL,
	[QTY_ORDERED] [decimal](13, 4) NULL,
	[QTY_SHIPPED] [decimal](13, 4) NULL,
	[QTY_BO] [decimal](13, 4) NULL,
	[QTY_ORIGINAL] [decimal](13, 4) NULL,
	[QTY_FRAC] [decimal](11, 4) NULL,
	[COST] [decimal](16, 6) NULL,
	[COST_LB] [decimal](12, 4) NULL,
	[FLAG_BOM] [nvarchar](1) NULL,
	[BOM_PARENT] [nvarchar](4) NULL,
	[FLAG_SERIALIZE] [nvarchar](1) NULL,
	[UM] [nvarchar](2) NULL,
	[UM_INVENTORY] [nvarchar](2) NULL,
	[FLAG_COGS] [nvarchar](1) NULL,
	[DATE_BILL] [datetime2](0) NULL,
	[COST_MATERIAL] [decimal](11, 2) NULL,
	[COST_LABOR] [decimal](11, 2) NULL,
	[COST_OUTSIDE] [decimal](11, 2) NULL,
	[COST_OVERHEAD] [decimal](11, 2) NULL,
	[COST_OTHER] [decimal](11, 2) NULL,
	[JOB] [nvarchar](6) NULL,
	[SUFFIX] [nvarchar](3) NULL,
	[LINE_TYPE] [nvarchar](1) NULL,
	[DATE_DUE] [datetime2](0) NULL,
	[GL_ACCOUNT] [nvarchar](15) NULL,
	[COMMISSION_TYPE] [nvarchar](5) NULL,
	[PRODUCT_LINE] [nvarchar](2) NULL,
	[FLAG_USES_MULT_QTY] [nvarchar](1) NULL,
	[EQUIPMENT_NO] [nvarchar](10) NULL,
	[GROUP_LINES] [nvarchar](10) NULL,
	[ITEM_SORTKEY] [nvarchar](12) NULL,
	[INFO_1] [nvarchar](20) NULL,
	[INFO_2] [nvarchar](20) NULL,
	[USER_1] [nvarchar](30) NULL,
	[USER_2] [nvarchar](30) NULL,
	[USER_3] [nvarchar](30) NULL,
	[USER_4] [nvarchar](30) NULL,
	[USER_5] [nvarchar](30) NULL,
	[FLAG_COMM_BUILT] [nvarchar](1) NULL,
	[FLAG_BILL_MATL] [nvarchar](1) NULL,
	[FLAG_DTL_BILL] [nvarchar](1) NULL,
	[REPEAT_FREQUENCY] [nvarchar](1) NULL,
	[REPEAT_BILL_DAY] [nvarchar](2) NULL,
	[DISCOUNT] [decimal](5, 4) NULL,
	[PRICE_CLASS_DISC] [decimal](5, 4) NULL,
	[PROD_LINE_DISC] [decimal](5, 4) NULL,
	[MARGIN] [decimal](7, 4) NULL,
	[FLAG_TAX_STATUS] [nvarchar](1) NULL,
	[PRICE_CODE] [bigint] NULL,
	[PRICE_DESCRIPTION] [nvarchar](30) NULL,
	[FREIGHT_PER_PIECE] [decimal](11, 6) NULL,
	[PRICE] [decimal](16, 6) NULL,
	[PRICE_DISCOUNT] [decimal](16, 6) NULL,
	[PRICE_LB] [decimal](16, 6) NULL,
	[EXTENSION] [decimal](16, 2) NULL,
	[AMT_DISCOUNT] [decimal](12, 2) NULL,
	[AMT_DISC_ORDER] [decimal](12, 2) NULL,
	[AMT_DISC_PR_CLASS] [decimal](12, 2) NULL,
	[AMT_DISC_PROD_LINE] [decimal](12, 2) NULL,
	[FRT_PER_PIECE_ORDER] [decimal](11, 6) NULL,
	[PRICE_ORDER] [decimal](16, 6) NULL,
	[PRICE_DISCOUNT_ORDER] [decimal](16, 6) NULL,
	[PRICE_LB_ORDER] [decimal](16, 6) NULL,
	[EXTENSION_ORDER] [decimal](16, 2) NULL,
	[AMT_DISCOUNT_ORDER] [decimal](12, 2) NULL,
	[AMT_DISC_ORDER_ORDER] [decimal](12, 2) NULL,
	[AMT_DISC_PR_ORDER] [decimal](12, 2) NULL,
	[AMT_DISC_PROD_ORDER] [decimal](12, 2) NULL,
	[TAX_SOURCE] [nvarchar](1) NULL,
	[TAX_STATE] [nvarchar](2) NULL,
	[TAX_ZIP] [nvarchar](13) NULL,
	[TAX_GEO_CODE] [nvarchar](2) NULL,
	[TAX_1] [nvarchar](3) NULL,
	[TAX_2] [nvarchar](3) NULL,
	[TAX_3] [nvarchar](3) NULL,
	[TAX_4] [nvarchar](3) NULL,
	[TAX_5] [nvarchar](3) NULL,
	[TAX_6] [nvarchar](3) NULL,
	[TAX_7] [nvarchar](3) NULL,
	[TAX_8] [nvarchar](3) NULL,
	[TAX_9] [nvarchar](3) NULL,
	[TAX_10] [nvarchar](3) NULL,
	[TAX_APPLY_1] [nvarchar](1) NULL,
	[TAX_APPLY_2] [nvarchar](1) NULL,
	[TAX_APPLY_3] [nvarchar](1) NULL,
	[TAX_APPLY_4] [nvarchar](1) NULL,
	[TAX_APPLY_5] [nvarchar](1) NULL,
	[TAX_APPLY_6] [nvarchar](1) NULL,
	[TAX_APPLY_7] [nvarchar](1) NULL,
	[TAX_APPLY_8] [nvarchar](1) NULL,
	[TAX_APPLY_9] [nvarchar](1) NULL,
	[TAX_APPLY_10] [nvarchar](1) NULL,
	[TAX_RATE_1] [decimal](5, 5) NULL,
	[TAX_RATE_2] [decimal](5, 5) NULL,
	[TAX_RATE_3] [decimal](5, 5) NULL,
	[TAX_RATE_4] [decimal](5, 5) NULL,
	[TAX_RATE_5] [decimal](5, 5) NULL,
	[TAX_RATE_6] [decimal](5, 5) NULL,
	[TAX_RATE_7] [decimal](5, 5) NULL,
	[TAX_RATE_8] [decimal](5, 5) NULL,
	[TAX_RATE_9] [decimal](5, 5) NULL,
	[TAX_RATE_10] [decimal](5, 5) NULL,
	[TAX_DESC_1] [nvarchar](30) NULL,
	[TAX_DESC_2] [nvarchar](30) NULL,
	[TAX_DESC_3] [nvarchar](30) NULL,
	[TAX_DESC_4] [nvarchar](30) NULL,
	[TAX_DESC_5] [nvarchar](30) NULL,
	[TAX_DESC_6] [nvarchar](30) NULL,
	[TAX_DESC_7] [nvarchar](30) NULL,
	[TAX_DESC_8] [nvarchar](30) NULL,
	[TAX_DESC_9] [nvarchar](30) NULL,
	[TAX_DESC_10] [nvarchar](30) NULL,
	[TAX_AMT_1] [decimal](11, 2) NULL,
	[TAX_AMT_2] [decimal](11, 2) NULL,
	[TAX_AMT_3] [decimal](11, 2) NULL,
	[TAX_AMT_4] [decimal](11, 2) NULL,
	[TAX_AMT_5] [decimal](11, 2) NULL,
	[TAX_AMT_6] [decimal](11, 2) NULL,
	[TAX_AMT_7] [decimal](11, 2) NULL,
	[TAX_AMT_8] [decimal](11, 2) NULL,
	[TAX_AMT_9] [decimal](11, 2) NULL,
	[TAX_AMT_10] [decimal](11, 2) NULL,
	[TAX_AMT_1_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_2_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_3_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_4_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_5_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_6_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_7_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_8_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_9_ORDER] [decimal](11, 2) NULL,
	[TAX_AMT_10_ORDER] [decimal](11, 2) NULL,
	[TAXABLE_TOT_1] [decimal](16, 2) NULL,
	[TAXABLE_TOT_2] [decimal](16, 2) NULL,
	[TAXABLE_TOT_3] [decimal](16, 2) NULL,
	[TAXABLE_TOT_4] [decimal](16, 2) NULL,
	[TAXABLE_TOT_5] [decimal](16, 2) NULL,
	[TAXABLE_TOT_6] [decimal](16, 2) NULL,
	[TAXABLE_TOT_7] [decimal](16, 2) NULL,
	[TAXABLE_TOT_8] [decimal](16, 2) NULL,
	[TAXABLE_TOT_9] [decimal](16, 2) NULL,
	[TAXABLE_TOT_10] [decimal](16, 2) NULL,
	[TAXABLE_TOT_1_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_2_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_3_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_4_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_5_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_6_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_7_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_8_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_9_ORDER] [decimal](16, 2) NULL,
	[TAXABLE_TOT_10_ORDER] [decimal](16, 2) NULL,
	[CREDIT_MEMO_FLAG] [nvarchar](1) NULL,
	[DATE_ORIG_INVOICE] [datetime2](0) NULL,
	[FLAG_TAX_ADJ] [nvarchar](1) NULL,
	[FLAG_RMA] [nvarchar](1) NULL,
	[ORDER_SOURCE] [nvarchar](1) NULL,
	[HISTORY_SOURCE] [nvarchar](1) NULL,
	[HISTORY_VERSION] [nvarchar](2) NULL,
	[FLAG_TEXTILE] [nvarchar](1) NULL,
	[CONTRACT] [bigint] NULL,
	[FRT_CURR_FLG] [nvarchar](1) NULL,
	[PART_PRICE_CODE] [nvarchar](3) NULL,
	[DD250_MARK_FOR] [nvarchar](6) NULL,
	[DD250_CLIN_NO] [nvarchar](4) NULL,
	[DD250_CLIN_CD] [nvarchar](2) NULL,
	[APPLY_MATL_SCHRG] [nvarchar](1) NULL,
	[MATL_SCHRG_FLAG] [nvarchar](1) NULL,
	[ADDER_PER_PIECE] [decimal](11, 6) NULL,
	[ADDER_EXT_DIFF] [decimal](12, 2) NULL,
	[CUR_ADDER_PER_PIECE] [decimal](11, 6) NULL,
	[CUR_ADDER_EXT_DIFF] [decimal](12, 2) NULL,
	[PRICE_BOM_COMP_FLAG] [nvarchar](1) NULL,
	[CARRIER_CD] [nvarchar](6) NULL,
	[NO_DLVR_BEF_DATE] [datetime2](0) NULL,
	[MUST_DLVR_DATE] [datetime2](0) NULL,
	[MATL_SCHRG_DATE] [datetime2](0) NULL,
	[SHIP_CHRG_FLAG] [nvarchar](1) NULL,
	[QUICK_SHP_FLAG] [nvarchar](1) NULL,
	[PHASE] [nvarchar](4) NULL,
	[LOTBIN_FLAG] [nvarchar](1) NULL,
	[CARTONS] [bigint] NULL,
	[PKGD_WEIGHT] [decimal](12, 4) NULL,
	[CNSGN_QTY_IVC] [decimal](13, 4) NULL,
	[SAR_SOURCE_FLG] [nvarchar](1) NULL,
	[BLANKET_NO] [nvarchar](7) NULL,
	[BLANKET_LINE] [nvarchar](4) NULL,
	[FACILITY] [nvarchar](3) NULL,
	[TAX_ZONE_1] [nvarchar](2) NULL,
	[TAX_ZONE_2] [nvarchar](2) NULL,
	[TAX_ZONE_3] [nvarchar](2) NULL,
	[TAX_ZONE_4] [nvarchar](2) NULL,
	[TAX_ZONE_5] [nvarchar](2) NULL,
	[TAX_ZONE_6] [nvarchar](2) NULL,
	[TAX_ZONE_7] [nvarchar](2) NULL,
	[TAX_ZONE_8] [nvarchar](2) NULL,
	[TAX_ZONE_9] [nvarchar](2) NULL,
	[TAX_ZONE_10] [nvarchar](2) NULL,
	[TAX_AUTH_TYPE_1] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_2] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_3] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_4] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_5] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_6] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_7] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_8] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_9] [nvarchar](1) NULL,
	[TAX_AUTH_TYPE_10] [nvarchar](1) NULL,
	[TAX_ACCT_1] [nvarchar](15) NULL,
	[TAX_ACCT_2] [nvarchar](15) NULL,
	[TAX_ACCT_3] [nvarchar](15) NULL,
	[TAX_ACCT_4] [nvarchar](15) NULL,
	[TAX_ACCT_5] [nvarchar](15) NULL,
	[TAX_ACCT_6] [nvarchar](15) NULL,
	[TAX_ACCT_7] [nvarchar](15) NULL,
	[TAX_ACCT_8] [nvarchar](15) NULL,
	[TAX_ACCT_9] [nvarchar](15) NULL,
	[TAX_ACCT_10] [nvarchar](15) NULL,
	[TAX_IMPORT_FLAG] [tinyint] NULL,
	[VAT_RULE_ID] [tinyint] NULL,
	[VAT_EXEMPT_TYPE] [tinyint] NULL,
	[TAX_IN_PRC_FLG] [bit] NULL,
	[TAX_PER_PIECE_2] [decimal](12, 2) NULL,
	[CUR_TAX_PER_PIECE_2] [decimal](12, 2) NULL,
	[MANUAL_TAX_FLG] [bit] NULL,
	[TAX_AUX_FLG] [bit] NULL,
	[SRVC_TYPE] [smallint] NULL,
	[INV_ALT_COST] [decimal](12, 4) NULL,
	[PRIMARY_GRP] [nvarchar](2) NULL,
	[SECONDARY_GRP] [nvarchar](2) NULL,
	[VAT_CNTRY_CD] [nvarchar](3) NULL,
	[VAT_EC_FLG] [bit] NULL,
	[TAX_PER_PIECE] [decimal](16, 6) NULL,
	[CUR_TAX_PER_PIECE] [decimal](16, 6) NULL,
	[XTNL_ORD_DISC_FLG] [bit] NULL,
	[COGS_FRT_COST] [decimal](11, 2) NULL,
	[SIX_DEC_TAX_FLG] [nvarchar](1) NULL,
	[TAX_CATG] [nvarchar](4) NULL,
	[TAX_INDEX_FLAG] [nvarchar](1) NULL,
	[TAX_ASGN_SRC] [bigint] NULL,
	[TAX_ORGN_ADR] [bigint] NULL,
	[TAX_ORGN_CITY] [nvarchar](15) NULL,
	[FILLER] [nvarchar](58) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]

GO


