CREATE TABLE [dwstage].[_V_SalesOrder]
(
	[SalesOrderNumber] [nchar](7) NULL,
	[SalesOrderLine] [nchar](4) NULL,
	[SOCreationDate] [date] NULL,
	[SODueDate] [date] NULL,
	[SOOrderSort] [nvarchar](20) NULL,
	[SOProjectType] [nvarchar](30) NULL,
	[SOBranch] [nchar](2) NULL,
	[SOShipVia] [nvarchar](20) NULL,
	[SOPrimaryGroup] [nchar](2) NULL,
	[SOShippingZone] [nchar](6) NULL,
	[SODateLastChanged] [date] NULL,
	[SOLastChangedBy] [nvarchar](8) NULL,
	[OLDateOrder] [date] NULL,
	[OLDateShipped] [date] NULL,
	[OLItemPromiseDate] [date] NULL,
	[OLDateItemProm] [date] NULL,
	[OLDateAddedDate] [date] NULL,
	[OLDeliverByDate] [date] NULL,
	[OLLastChangedBy] [nvarchar](8) NULL,
	[OLCustomerPart] [nvarchar](20) NULL,
	[OLPriceGroupID] [nvarchar](20) NULL,
	[OLSOGroupID] [nvarchar](20) NULL,
	[OLUser1] [nvarchar](30) NULL,
	[OLUser2] [nvarchar](30) NULL,
	[OLTrackingNotes] [nvarchar](30) NULL,
	[OLUser4] [nvarchar](30) NULL,
	[OLLineShipVia] [nvarchar](30) NULL,
	[OLLineType] [nchar](1) NULL,
	[OLFlagSOtoWO] [nchar](1) NULL,
	[OLFlagPurchased] [nchar](1) NULL,
	[OLInactive] [bit] NULL,
	[Price] [decimal](16, 4) NULL,
	[Cost] [decimal](16, 4) NULL,
	[ExtenedPrice] [decimal](16, 4) NULL,
	[Margin] [decimal](16, 4) NULL,
	[QtyOriginal] [decimal](16, 4) NULL,
	[QtyAllocated] [decimal](16, 4) NULL,
	[QuantityOrdered] [decimal](16, 4) NULL,
	[Qty_Shipped] [decimal](16, 4) NULL,
	[QtyBackOrdered] [decimal](16, 4) NULL,
	[PriceDiscount] [decimal](16, 4) NULL,
	[PricePerPound] [decimal](16, 4) NULL,
	[DiscountAmount] [decimal](16, 4) NULL,
	[OrderDiscount] [decimal](16, 4) NULL,
	[ProductClassDiscountAmount] [decimal](16, 4) NULL,
	[ProductLineDiscount] [decimal](16, 4) NULL,
	[OrderDiscountAmount] [decimal](16, 4) NULL,
	[PriceClassDiscount] [decimal](16, 4) NULL,
	[ProductLineDiscountAmount] [decimal](16, 4) NULL,
	[OrderPrice] [decimal](16, 4) NULL,
	[OrderDiscountPrice] [decimal](16, 4) NULL,
	[OrderPricePerPound] [decimal](16, 4) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]
GO

