CREATE TABLE [dwstage].[AP_OPEN_ITEMS](
	[VENDOR] [char](7) NULL,
	[INVOICE] [char](15) NULL,
	[BATCH_CODE] [char](2) NULL,
	[BATCH_NUM] [char](5) NULL,
	[BATCH_LINE] [char](4) NULL,
	[DATE_BATCH] [char](6) NULL,
	[TERRITORY] [char](2) NULL,
	[AREA] [char](2) NULL,
	[GL_ACCOUNT] [char](15) NULL,
	[DATE_INVOICE] [char](6) NULL,
	[DATE_INVOICE_J] [numeric](5, 0) NULL,
	[AMT_INVOICE] [numeric](16, 2) NULL,
	[DATE_INVOICE_DUE] [char](6) NULL,
	[DATE_INVOICE_DUE_J] [numeric](5, 0) NULL,
	[DISCOUNT_INVOICE] [numeric](10, 2) NULL,
	[PURCHASE_ORDER] [char](7) NULL,
	[BUYER] [char](3) NULL,
	[CHECK_NUM] [char](20) NULL,
	[DATE_CHECK] [char](6) NULL,
	[CHECK_CODE] [char](1) NULL,
	[RECEIVER] [char](6) NULL,
	[JOB] [char](7) NULL,
	[SUFFIX] [char](4) NULL,
	[SEQ] [char](6) NULL,
	[FREIGHT] [numeric](11, 2) NULL,
	[OTHER] [numeric](11, 2) NULL,
	[CHECK_DESC] [char](30) NULL,
	[VOUCHER] [char](7) NULL,
	[PO_PARTIAL_RECEIPT] [char](1) NULL,
	[AMT_PARTIAL_TEMP] [numeric](16, 2) NULL,
	[PURCHASE_ORDER_PTL] [char](1) NULL,
	[FLAG_PAY_HOLD] [char](1) NULL,
	[DATE_FLAG_TO_PURGE] [char](6) NULL,
	[PAYMENT_SEQ] [char](1) NULL,
	[PO_LINE] [char](3) NULL,
	[FLAG_CHANGE] [char](1) NULL,
	[AMT_TRANSACTION] [numeric](16, 2) NULL,
	[FLAG_PAY_SELECT] [char](1) NULL,
	[EXCHANGE_CURR] [char](3) NULL,
	[DATE_EXCHANGE] [char](8) NULL,
	[EXCHANGE_RATE] [numeric](10, 5) NULL,
	[EXCHANGE_AMT] [numeric](16, 2) NULL,
	[FLAG_CK_CLEARED] [char](1) NULL,
	[FILLER2] [char](1) NULL,
	[EXCHANGE_AMT_INV] [numeric](16, 2) NULL,
	[PACK_LIST] [char](16) NULL,
	[USERID] [char](8) NULL,
	[PAY_WITH_CCARD] [char](1) NULL,
	[CCARD_VENDOR] [char](6) NULL,
	[ORIG_VENDOR] [char](6) NULL,
	[PAY_ACH] [char](1) NULL,
	[TAXABLE_FLG] [bit] NULL,
	[TAX_CODE] [char](5) NULL,
	[VAT_RULE] [numeric](3, 0) NULL,
	[VEND_TAXABLE_AMT] [numeric](16, 2) NULL,
	[VEND_TAX_AMT] [numeric](10, 2) NULL,
	[VEND_RETENTION_AMT] [numeric](10, 2) NULL,
	[INVC_TAXABLE_AMT] [numeric](16, 2) NULL,
	[INVC_TAX_AMT] [numeric](10, 2) NULL,
	[INVC_RETENTION_AMT] [numeric](10, 2) NULL,
	[INCL_IN_VAT_RPT] [char](1) NULL,
	[EXCH_RATE_OVERRIDE] [char](1) NULL,
	[ORIG_EXCH_RATE] [numeric](10, 5) NULL,
	[ORIG_EXCH_DATE] [char](8) NULL,
	[MODIFY_DISC_AMT] [char](1) NULL,
	[PAYMENT_CURR] [char](3) NULL,
	[FILLER] [char](26) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]
GO