CREATE TABLE [dwstage].[INVENTORY_MST3](
	[PART] [char](20) NULL,
	[LOCATION] [char](2) NULL,
	[MATL_SCHRG_TYPE] [char](20) NULL,
	[HM_FLAG] [char](1) NULL,
	[FRT_CLASS] [char](5) NULL,
	[PALLET_FLAG] [char](1) NULL,
	[CNTNRS_PER_PALLET] [numeric](8, 0) NULL,
	[PKGD_BY] [char](1) NULL,
	[PCS_PER_CNTNR] [numeric](8, 0) NULL,
	[DFLT_CARTON_CD] [char](11) NULL,
	[DFLT_PALLET_CD] [char](11) NULL,
	[COMM_DESCR] [char](30) NULL,
	[FILL_DESC] [char](20) NULL,
	[NMFC_NO] [char](6) NULL,
	[PKGD_WEIGHT] [numeric](12, 4) NULL,
	[PKG_COMPONENTS] [char](1) NULL,
	[LOT_TO_LOT] [char](1) NULL,
	[DROP_SHIP] [char](1) NULL,
	[CONSUMP_CONV] [numeric](11, 5) NULL,
	[BOM_REF] [char](1) NULL,
	[STOCK_BIN] [char](6) NULL,
	[GEN_PART_SEQ] [char](1) NULL,
	[GEN_PART_NBR] [char](17) NULL,
	[NMFC_SUB_NO] [char](4) NULL,
	[IC_VENDOR] [char](6) NULL,
	[FILL_VEND] [char](1) NULL,
	[MATL_SCHRG_DATE] [char](8) NULL,
	[PART_CREATE_DATE] [char](8) NULL,
	[SHELF_LIFE] [char](1) NULL,
	[REQUIRES_TESTING] [char](1) NULL,
	[BIZ_WEB_PART_FLG] [char](1) NULL,
	[AUTO_LOT_NUM] [char](1) NULL,
	[COST_DATE] [char](8) NULL,
	[AGING] [numeric](1, 0) NULL,
	[PROJECT_GROUP] [char](6) NULL,
	[TEMP_PURCH] [char](1) NULL,
	[CONSUMPTION_PERCENT] [numeric](6, 4) NULL,
	[DO_NOT_CALC_ABC] [char](1) NULL,
	[EXCL_MULTI_PART_WO] [char](1) NULL,
	[LABEL_RPT_ID] [char](6) NULL,
	[PO_CERTS_REQD] [char](1) NULL,
	[THICKNESS] [numeric](7, 4) NULL,
	[ROLL] [char](1) NULL,
	[INCL_SPCD] [char](1) NULL,
	[NO_DISC] [char](1) NULL,
	[COST_NO_OVHD] [numeric](14, 6) NULL,
	[STANDARD_COST_QTY] [numeric](14, 6) NULL,
	[TRIGGER_PART] [char](1) NULL,
	[VAT_PRODUCT_TYP] [char](5) NULL,
	[TAX_EXEMPT_FLG] [char](1) NULL,
	[PART_CREATE_USER] [char](8) NULL,
	[DO_NOT_BACKFLUSH] [char](1) NULL,
	[MODEL_BOM_FLAG] [char](1) NULL,
	[FILLER4] [char](4) NULL,
	[MFG_LEAD] [numeric](4, 0) NULL,
	[MFG_QTY_MINIMUM] [numeric](14, 6) NULL,
	[MFG_QTY_MULTIPLE] [numeric](14, 6) NULL,
	[USE_DIMENSION_CALC] [bit] NULL,
	[FILLER1] [char](142) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]

GO


