CREATE TABLE [dbo].[AR_OPEN_ITEMS](
	[CUSTOMER] [char](7) NULL,
	[INVOICE] [char](7) NULL,
	[BATCH_CODE] [char](2) NULL,
	[BATCH_NUM] [char](5) NULL,
	[BATCH_LINE] [char](4) NULL,
	[DATE_INVOICE] [char](6) NULL,
	[DATE_TRANSACTION] [char](6) NULL,
	[DATE_RETAIN] [char](6) NULL,
	[FLAG_RETAIN] [char](1) NULL,
	[AMT_TRANS_TOTAL] [numeric](16, 2) NULL,
	[GL_ACCOUNT] [char](15) NULL,
	[AMT_INVOICE] [numeric](16, 2) NULL,
	[SALESPERSON] [char](3) NULL,
	[REFERENCE] [char](22) NULL,
	[COST] [numeric](16, 2) NULL,
	[TERRITORY] [char](2) NULL,
	[AREA] [char](2) NULL,
	[STATE] [char](2) NULL,
	[DATE_INVOICE_CYMD] [char](8) NULL,
	[FACTOR_FLAG] [char](1) NULL,
	[MAN_PURGE_FLAG] [char](1) NULL,
	[CHANGE_FLAG] [char](1) NULL,
	[REFUND_CM_BATCH] [char](5) NULL,
	[REFUND_CM_LINE] [numeric](3, 0) NULL,
	[REFUND_CK_NO] [char](20) NULL,
	[REFUND_CK_CLEAR] [char](1) NULL,
	[REFUND_CK_CODE] [char](1) NULL,
	[EXCHANGE_CURR] [char](3) NULL,
	[DATE_EXCHANGE] [char](8) NULL,
	[EXCHANGE_RATE] [numeric](10, 5) NULL,
	[EXCHANGE_AMT] [numeric](16, 2) NULL,
	[EXCHANGE_AMT_TOT] [numeric](16, 2) NULL,
	[ORDER_NO] [char](7) NULL,
	[ORDER_SUFFIX] [char](4) NULL,
	[TERMS_CODE] [char](1) NULL,
	[DUE_DATE] [char](8) NULL,
	[DISC_DATE] [char](8) NULL,
	[FRT_AMT_CO_CURR] [numeric](11, 2) NULL,
	[TAX_AMT_CO_CURR] [numeric](11, 2) NULL,
	[FRT_AMT_OE_CURR] [numeric](11, 2) NULL,
	[TAX_AMT_OE_CURR] [numeric](11, 2) NULL,
	[INVC_DISC_OE_CURR] [numeric](10, 2) NULL,
	[INVC_DISC_CO_CURR] [numeric](10, 2) NULL,
	[PAYMENT_TYPE] [char](2) NULL,
	[PREPAID_FLAG] [char](1) NULL,
	[PCK_NO] [numeric](7, 0) NULL,
	[TAXABLE_AMT_CO_CURR] [numeric](16, 2) NULL,
	[RETENTION_CO_CURR] [numeric](16, 2) NULL,
	[TAXABLE_AMT_OE_CURR] [numeric](16, 2) NULL,
	[RETENTION_OE_CURR] [numeric](16, 2) NULL,
	[TAXABLE_FLG] [bit] NULL,
	[EXCH_RATE_OVERRIDE] [char](1) NULL,
	[ORIG_EXCH_RATE] [numeric](10, 5) NULL,
	[ORIG_EXCH_DATE] [char](8) NULL,
	[SALES_COMM_ADDED] [char](1) NULL,
	[PAYMENT_CURR] [char](3) NULL,
	[FILLER] [char](27) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]