CREATE TABLE [dbo].[_V_Inventory](
	[PartID] [nchar](20) NULL,
	[DateLastChg] [date] NULL,
	[WhoChgLast] [nchar](8) NULL,
	[Price] [decimal](13, 5) NULL,
	[CodeABC] [nchar](1) NULL,
	[ProductLine] [nchar](2) NULL,
	[PartDescription] [nvarchar](100) NULL,
	[UM] [nchar](3) NULL,
	[Obsolete] [nchar](1) NULL,
	[CodeSort] [nchar](10) NULL,
	[MaterialLeadTime] [decimal](4, 0) NULL,
	[SerializeFlag] [nchar](1) NULL,
	[SourceCode] [nchar](12) NULL,
	[PrimaryVendor] [nchar](20) NULL,
	[PriceGroupID] [nchar](20) NULL,
	[SOGroupID] [nchar](20) NULL,
	[AltDescription1] [nchar](30) NULL,
	[AltDescription2] [nchar](30) NULL,
	[RequiresInspection] [nchar](1) NULL,
	[ShelfLife] [nchar](1) NULL,
	[VatProductType] [nchar](5) NULL,
	[TaxExemptFlag] [nchar](1) NULL,
	[Location] [nchar](2) NULL,
	[BIN] [nchar](6) NULL,
	[DateLastUsage] [date] NULL,
	[DateLastAudit] [date] NULL,
	[DateCycle] [date] NULL,
	[CodeBOM] [nchar](1) NULL,
	[CodeDiscount] [nchar](1) NULL,
	[CodeTotal] [nchar](1) NULL,
	[PriorUsage] [decimal](7, 0) NULL,
	[AltCostAmt] [decimal](16, 6) NULL,
	[MinMultiple] [decimal](12, 4) NULL,
	[FloorStockingLevel] [decimal](12, 4) NULL,
	[QtyOnHand] [decimal](12, 4) NULL,
	[QtyReorder] [decimal](12, 4) NULL,
	[QtyOnOrderPO] [decimal](12, 4) NULL,
	[QtyOnOrderWO] [decimal](12, 4) NULL,
	[QtyRequired] [decimal](12, 4) NULL,
	[AmtCost] [decimal](12, 4) NULL,
	[UsageJanuary] [decimal](7, 0) NULL,
	[UsageFebruary] [decimal](7, 0) NULL,
	[UsageMarch] [decimal](7, 0) NULL,
	[UsageApril] [decimal](7, 0) NULL,
	[UsageMay] [decimal](7, 0) NULL,
	[UsageJune] [decimal](7, 0) NULL,
	[UsageJuly] [decimal](7, 0) NULL,
	[UsageAugust] [decimal](7, 0) NULL,
	[UsageSeptember] [decimal](7, 0) NULL,
	[UsageOctober] [decimal](7, 0) NULL,
	[UsageNovember] [decimal](7, 0) NULL,
	[UsageDecember] [decimal](7, 0) NULL,
	[Qty_Allocated] [decimal](15, 6) NULL,
	[ETL_TblNbr] [int] NULL,
	[ETL_Batch] [int] NULL,
	[ETL_Completed] [datetime] NULL
) ON [PRIMARY]
GO