Create View
[dw].[SV_DimEmployee]
As
SELECT [DimEmployee_Key]
      ,[EmployeeID]
      ,[EmployeeRecordType]
      ,[EmployeeName]
      ,[EmployeeAddress]
      ,[EmployeeCity]
      ,[EmployeeState]
      ,[EmployeePostalCode]
      ,[EmployeeGender]
      ,[EmployeeHireDate]
      ,[EmployeeTerminationDate]
      ,[EmployeeDepartment]
      ,[EmployeeIsSalesperson]
      ,[EmployeeInitials]
      ,[DWEffectiveStartDate]
      ,[DWEffectiveEndDate]
      ,[DWIsCurrent]
  FROM [dw].[DimEmployee]
GO
