CREATE VIEW [dwstage].[V_Inventory_All]
AS
SELECT        A.PART, A.LOCATION, A.CODE_ABC, A.PRODUCT_LINE, A.BIN, A.DESCRIPTION, A.UM_PURCHASING, A.UM_INVENTORY, A.FACTOR_CONVERSION, A.QTY_ORDER, A.QTY_SAFETY, A.QTY_ONHAND, 
                         A.QTY_REORDER, A.QTY_ONORDER_PO, A.QTY_ONORDER_WO, A.QTY_REQUIRED, A.AMT_COST, A.QTY_USAGE_MO_01, A.QTY_USAGE_MO_02, A.QTY_USAGE_MO_03, A.QTY_USAGE_MO_04, 
                         A.QTY_USAGE_MO_05, A.QTY_USAGE_MO_06, A.QTY_USAGE_MO_07, A.QTY_USAGE_MO_08, A.QTY_USAGE_MO_09, A.QTY_USAGE_MO_10, A.QTY_USAGE_MO_11, A.QTY_USAGE_MO_12, A.PRIOR_USAGE, 
                         dwstage.udf_cv_nvarchar6_to_date(A.DATE_LAST_USAGE) AS DATE_LAST_USAGE, A.AMT_PRICE, A.OBSOLETE_FLAG, A.CODE_BOM, A.CODE_DISCOUNT, A.CODE_TOTAL, A.CODE_SORT, A.QTY_RECVD_NOT_INSP, 
                         A.QTY_MFG_REQMTS, A.QTY_CURRENT_USAGE, A.YEAR_LAST_ROLL, dwstage.udf_cv_nvarchar6_to_date(A.DATE_LAST_AUDIT) AS DATE_LAST_AUDIT, A.CODE_EXTRA_DESC, A.PCT_ORDER_DISC, 
                         A.TIME_MATERIAL_LEAD, A.PRIM_DIM, A.SEC_DIM, A.QTY_BEGINNING, A.AMT_BEG_COST, A.CODE_EXCEPTION, A.CODE_PERM_FIX, dwstage.udf_cv_nvarchar6_to_date(A.DATE_EXCEPTION) AS DATE_EXCEPTION, 
                         A.CTR_BACK_ORDER, A.AMT_ALT_COST, dwstage.udf_cv_nvarchar6_to_date(A.DATE_LAST_CHG) AS DATE_LAST_CHG, A.WHO_CHG_LAST, A.TRM_CHG_LAST, A.LENGTH_RAW_MATL, A.WIDTH_RAW_MATL, 
                         A.DENSITY_RAW_MATL, A.CODE_RM_SHAPE, A.QTY_LAST_ONHAND, dwstage.udf_cv_nvarchar6_to_date(A.DATE_LAST_VERIFY) AS DATE_LAST_VERIFY, A.FLAG_DROP, A.FLAG_6_COST, A.FLAG_SERIALIZE, 
                         A.FLAG_INACTIVE, A.FLAG_WARRANTY, A.USE_ZERO_LEAD, B.QTY_MAXIMUM, B.HRS_STANDARD, B.LBS, B.CODE_SOURCE, B.NAME_VENDOR, B.TEXT_INFO1, B.TEXT_INFO2, B.DESCRIPTION_2, 
                         B.DESCRIPTION_3, B.AMT_COST_1, B.AMT_COST_2, B.AMT_COST_3, dwstage.udf_cv_nvarchar6_to_date(B.DATE_CYCLE) AS DATE_CYCLE, B.LIFO_BASE, B.SIX_DECIMAL_COST, B.WT_PER_FOOT, 
                         B.CUTTING_CHARGE, B.SHP_CNV_FACTOR, B.SHIP_UM, B.LENGTH, B.WIDTH, B.WARRANTY_TYPE, B.PROP_CODE, B.REQUIRES_INSP, B.BASE_PART, B.PRICE_CATG, B.ISSUE_UM, B.PART_PRICE_CODE, 
                         C.MATL_SCHRG_TYPE, C.HM_FLAG, C.FRT_CLASS, C.PALLET_FLAG, C.CNTNRS_PER_PALLET, C.PKGD_BY, C.PCS_PER_CNTNR, C.DFLT_CARTON_CD, C.DFLT_PALLET_CD, C.COMM_DESCR, C.NMFC_NO, 
                         C.PKGD_WEIGHT, C.PKG_COMPONENTS, C.LOT_TO_LOT, C.DROP_SHIP, C.CONSUMP_CONV, C.BOM_REF, C.STOCK_BIN, C.GEN_PART_SEQ, C.GEN_PART_NBR, C.NMFC_SUB_NO, C.IC_VENDOR, 
                         dwstage.udf_cv_nvarchar8_to_date(C.MATL_SCHRG_DATE) AS MATL_SCHRG_DATE, dwstage.udf_cv_nvarchar8_to_date(C.PART_CREATE_DATE) AS PART_CREATE_DATE, C.SHELF_LIFE, C.REQUIRES_TESTING, 
                         C.BIZ_WEB_PART_FLG, C.AUTO_LOT_NUM, dwstage.udf_cv_nvarchar8_to_date(C.COST_DATE) AS COST_DATE, C.AGING, C.PROJECT_GROUP, C.TEMP_PURCH, C.CONSUMPTION_PERCENT, C.DO_NOT_CALC_ABC, 
                         C.EXCL_MULTI_PART_WO, C.LABEL_RPT_ID, C.PO_CERTS_REQD, C.THICKNESS, C.ROLL, C.INCL_SPCD, C.NO_DISC, C.COST_NO_OVHD, C.STANDARD_COST_QTY, C.TRIGGER_PART, C.VAT_PRODUCT_TYP, 
                         C.TAX_EXEMPT_FLG, C.PART_CREATE_USER, C.DO_NOT_BACKFLUSH, C.MODEL_BOM_FLAG, C.MFG_LEAD, C.MFG_QTY_MINIMUM, C.MFG_QTY_MULTIPLE, C.USE_DIMENSION_CALC, A.ETL_Batch, 
                         A.ETL_Completed
FROM            dwstage.INVENTORY_MSTR AS A LEFT OUTER JOIN
                         dwstage.INVENTORY_MST2 AS B ON A.PART = B.PART AND A.LOCATION = B.LOCATION LEFT OUTER JOIN
                         dwstage.INVENTORY_MST3 AS C ON A.PART = C.PART AND A.LOCATION = C.LOCATION
GO

