CREATE VIEW [dwstage].[V_CustomerShipTo] 
AS 
SELECT 
CUSTOMER_SHIPTO.CUSTOMER,
CUSTOMER_SHIPTO.REC,
CUSTOMER_SHIPTO.NAME_CUSTOMER_SHIP,
CUSTOMER_SHIPTO.ADDRESS1_SHIP,
CUSTOMER_SHIPTO.ADDRESS2_SHIP,
CUSTOMER_SHIPTO.CITY_SHIP,
CUSTOMER_SHIPTO.STATE_SHIP,
CUSTOMER_SHIPTO.CODE_ZIP_SHIP,
CUSTOMER_SHIPTO.COUNTRY_SHIP,
CUSTOMER_SHIPTO.COUNTY_SHIP,
CUSTOMER_SHIPTO.ATTENTION_SHIP,
CUSTOMER_SHIPTO.SHIP_VIA,
CUSTOMER_SHIPTO.CODE_SHIP_COLLECT,
CUSTOMER_SHIPTO.FLAG_EDI_ASN,
CUSTOMER_SHIPTO.FLAG_EDI_INVOICE,
CUSTOMER_SHIPTO.FRT_ZONE,
CUSTOMER_SHIPTO.INTL_ADRS,
CUSTOMER_SHIPTO.T_COUNTRY,
CUSTOMER_SHIPTO.AREA,
CUSTOMER_SHIPTO.TELE,
CUSTOMER_SHIPTO.FAX,
CUSTOMER_SHIPTO.DISCOUNT,
CUSTOMER_SHIPTO.BOL_MULTI_ID,
CUSTOMER_SHIPTO.INTL_CITY_FLD,
CUSTOMER_SHIPTO.INTL_CRTY_FLD,
Customer_ShipTo.ETL_Batch,
CUSTOMER_SHIPTO.ETL_Completed

FROM CUSTOMER_SHIPTO CUSTOMER_SHIPTO 
WHERE CUSTOMER_SHIPTO.REC = '3' 
GO


