CREATE VIEW [dwstage].[V_LoadLkpJobHeaderHist]
AS
SELECT 

  stage.JOB
, stage.SUFFIX
, stage.PART
, PRODUCT_LINE
, ROUTER
, stage.[PRIORITY]
, stage.[DESCRIPTION]
, CUSTOMER
, CUSTOMER_PO
, COMMENTS_1
, BIN
, WO_RTR_RELEASED 
, FLAG_WO_PRTD
, FLAG_HOLD
, PARENT_WO
, PARENT_SUFFIX_PARENT
, SALES_ORDER
, SALES_ORDER_LINE
, FLAG_SERIALIZE
, JOB_LOCKED
----------------------------------
, DATE_OPENED
, DATE_DUE
, DATE_CLOSED
, DATE_START
, DATE_SCH_CMPL_INF
, DATE_SCH_CMPL_FIN
, DATE_LAST_SCH_INF
, DATE_DTE_DUE_REV
, DATE_START_OTHER
, DATE_SHIP_1
, DATE_SHIP_2
, DATE_SHIP_3
, DATE_SHIP_4
, DATE_LAST_SCH_FIN
, DATE_DUE_NEW
, CTR_DATE_REVUE_DUE
, CTR_DATE_DUE_NEW
, DATE_MATERIAL_DUE
, CTR_DATE_MATL_DUE
, DATE_MATL_ORDER
, DATE_RELEASED
--------------------------------
, SCHED_DUE_DATE
, QTY_ORDER
, QTY_COMPLETED
, AMT_PRICE_PER_UNIT
, AMT_SALES
, AMT_MATERIAL
, NUM_HOURS
, AMT_LABOR
, AMT_OVERHEAD
, AMT_PARTIAL_SHPMNT
, QTY_SHIP_1
, QTY_CUSTOMER
, PARTIAL_MATERIAL
, PARTIAL_LABOR
, PARTIAL_OVERHEAD
, PARTIAL_OUTSIDE
, OUTS

--, [Type1RecordHash]		      = CAST(0 AS VARBINARY(64))
, [Type1RecordHash]			  = HASHBYTES('SHA2_256',
																	
+ stage.JOB
+ stage.SUFFIX
+ stage.PART
+ PRODUCT_LINE
+ ROUTER
+ stage.[PRIORITY]
+ stage.[DESCRIPTION]
+ CUSTOMER
+ CUSTOMER_PO
+ COMMENTS_1
+ BIN
+ WO_RTR_RELEASED
+ FLAG_WO_PRTD
+ FLAG_HOLD
+ PARENT_WO
+ PARENT_SUFFIX_PARENT
+ SALES_ORDER
+ SALES_ORDER_LINE
+ FLAG_SERIALIZE
+ JOB_LOCKED


+ CAST(DATE_OPENED AS NVARCHAR(20))
+ CAST(DATE_DUE AS NVARCHAR(20))
+ CAST(DATE_CLOSED AS NVARCHAR(20))
+ CAST(DATE_START AS NVARCHAR(20))
+ CAST(DATE_SCH_CMPL_INF AS NVARCHAR(20))
+ CAST(DATE_SCH_CMPL_FIN AS NVARCHAR(20))
+ CAST(DATE_LAST_SCH_INF AS NVARCHAR(20))
+ CAST(DATE_DTE_DUE_REV AS NVARCHAR(20))
+ CAST(DATE_START_OTHER AS NVARCHAR(20))
+ CAST(DATE_SHIP_1 AS NVARCHAR(20))
+ CAST(DATE_SHIP_2 AS NVARCHAR(20))
+ CAST(DATE_SHIP_3 AS NVARCHAR(20))
+ CAST(DATE_SHIP_4 AS NVARCHAR(20))
+ CAST(DATE_LAST_SCH_FIN AS NVARCHAR(20))
+ CAST(DATE_DUE_NEW AS NVARCHAR(20))
+ CAST(CTR_DATE_REVUE_DUE AS NVARCHAR(20))
+ CAST(CTR_DATE_DUE_NEW AS NVARCHAR(20))
+ CAST(DATE_MATERIAL_DUE AS NVARCHAR(20))
+ CAST(CTR_DATE_MATL_DUE AS NVARCHAR(20))
+ CAST(DATE_MATL_ORDER AS NVARCHAR(20))
+ CAST(DATE_RELEASED AS NVARCHAR(20))


+ CAST(SCHED_DUE_DATE AS NVARCHAR(20))
+ CAST(QTY_ORDER AS NVARCHAR(20))
+ CAST(QTY_COMPLETED AS NVARCHAR(20))
+ CAST(AMT_PRICE_PER_UNIT AS NVARCHAR(20))
+ CAST(AMT_SALES AS NVARCHAR(20))
+ CAST(AMT_MATERIAL AS NVARCHAR(20))
+ CAST(NUM_HOURS AS NVARCHAR(20))
+ CAST(AMT_LABOR AS NVARCHAR(20))
+ CAST(AMT_OVERHEAD AS NVARCHAR(20))
+ CAST(AMT_PARTIAL_SHPMNT AS NVARCHAR(20))
+ CAST(QTY_SHIP_1 AS NVARCHAR(20))
+ CAST(QTY_CUSTOMER AS NVARCHAR(20))
+ CAST(PARTIAL_MATERIAL AS NVARCHAR(20))
+ CAST(PARTIAL_LABOR AS NVARCHAR(20))
+ CAST(PARTIAL_OVERHEAD AS NVARCHAR(20))
+ CAST(PARTIAL_OUTSIDE AS NVARCHAR(20))
+ CAST(OUTS AS NVARCHAR(20))
															
)


FROM 
	
	dwstage._V_JOB_HEADER_HIST Stage



GO
