CREATE VIEW [dwstage].[V_Customer_Master]
AS
SELECT        CUSTOMER, REC, NAME_CUSTOMER, ADDRESS1, ADDRESS2, CITY, STATE, ZIP, COUNTRY, COUNTY, ATTENTION, SALESPERSON, INTL_ADDR, TERRITORY, CODE_AREA, CREDIT, TELEPHONE, 
                         CRM_RES_LEV, ASSGN_USR_GRP, NORMAL_GL_ACCOUNT, FLAG_BALANCE_FWD, FLAG_PRINT_STATE, FLAG_CREDIT_HOLD, CHANGE_MODE, INTERCOMPANY, ETL_Batch, ETL_Completed
FROM            dwstage.CUSTOMER_MASTER AS CUSTOMER_MASTER
WHERE        (REC = '1')
GO


